import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/authz";
import { ensureComplianceCatalog } from "@/lib/compliance";
import { isModuleSlug, moduleDefinitions } from "@/lib/modules";
import { PageHeader } from "@/components/page-header";
import { WorkflowForm } from "@/components/workflow-form";
import { ComplianceBrowser } from "@/components/compliance-browser";
import { Card, CardContent } from "@/components/ui/card";
import { formatDate } from "@/lib/utils";

export default async function ModulePage({ params }: { params: Promise<{ module: string }> }) { const { module }=await params; if(!isModuleSlug(module)) notFound(); const session=await requireSession(); const definition=moduleDefinitions[module]; const serializable={titleLabel:definition.titleLabel,detailsLabel:definition.detailsLabel,outcomeLabel:definition.outcomeLabel,defaultOutcome:definition.defaultOutcome}; await ensureComplianceCatalog(session.user.tenantId); const [records,references]=await Promise.all([db.grcRecord.findMany({where:{tenantId:session.user.tenantId,module},orderBy:{createdAt:"desc"},take:20}),db.complianceReference.findMany({where:{tenantId:session.user.tenantId},orderBy:[{framework:"asc"},{reference:"asc"}]})]); return <><PageHeader eyebrow={definition.eyebrow} title={definition.title} description={definition.description}/><div className={`grid items-start gap-5 ${module==="compliance"||module==="assessments" ? "xl:grid-cols-[1fr_430px]" : ""}`}><div className="space-y-5"><WorkflowForm module={module} definition={serializable} userName={session.user.name ?? session.user.email ?? "Workspace owner"}/><section><h2 className="mb-3 text-xs font-bold uppercase text-muted-foreground">Recent records</h2><div className="space-y-2">{records.map(record=><Card key={record.id}><CardContent className="grid gap-3 pt-5 sm:grid-cols-[1fr_auto]"><div><p className="text-sm font-bold">{record.title}</p><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{record.details}</p></div><div className="text-left sm:text-right"><p className="text-[10px] font-bold text-primary">{record.status}</p><p className="mt-1 text-[10px] text-muted-foreground">{record.dueDate ? formatDate(record.dueDate) : "No due date"}</p></div></CardContent></Card>)}{!records.length&&<p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No records yet. Complete the structured entry above.</p>}</div></section></div>{(module==="compliance"||module==="assessments")&&<ComplianceBrowser references={references} compact/>}</div></>; }