import { PageHeader } from "@/components/page-header";
import { ReviewForm } from "@/components/lifecycle-forms";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { requireSession } from "@/lib/authz";
import { db } from "@/lib/db";
import { formatDate, formatEnum } from "@/lib/utils";

export default async function ReviewsPage() {
  const session = await requireSession(); const tenantId = session.user.tenantId;
  const [risks, reviews, actions] = await Promise.all([
    db.risk.findMany({ where: { tenantId, deletedAt: null }, select: { id: true, reference: true, title: true, nextReviewDate: true, status: true }, orderBy: { nextReviewDate: "asc" } }),
    db.riskReview.findMany({ where: { tenantId }, include: { risk: { select: { reference: true, title: true } }, reviewer: { select: { name: true } } }, orderBy: { scheduledFor: "asc" }, take: 100 }),
    db.treatmentAction.findMany({ where: { tenantId, dueDate: { lt: new Date() }, status: { in: ["NOT_STARTED", "IN_PROGRESS", "BLOCKED"] } }, include: { treatmentPlan: { include: { risk: { select: { reference: true } } } }, owner: { select: { name: true } } }, orderBy: { dueDate: "asc" }, take: 100 }),
  ]);
  return <><PageHeader eyebrow="Review governance" title="Reviews and escalation" description="Record review outcomes, request reassessment, maintain the next review date, and identify overdue treatment work."/><div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Card><CardHeader><h2 className="text-sm font-bold">Record a review</h2></CardHeader><CardContent><ReviewForm risks={risks.map((risk) => ({ value: risk.id, label: `${risk.reference} · ${risk.title}` }))}/></CardContent></Card><div className="grid gap-5"><Card><CardHeader><h2 className="text-sm font-bold">Review schedule</h2></CardHeader><CardContent className="p-0"><div className="divide-y">{risks.map((risk) => <div key={risk.id} className="flex flex-wrap items-center justify-between gap-3 p-4 text-xs"><div><p className="font-semibold">{risk.reference} · {risk.title}</p><p className="mt-1 text-muted-foreground">Next review {formatDate(risk.nextReviewDate)}</p></div><Badge>{formatEnum(risk.status)}</Badge></div>)}</div></CardContent></Card><Card><CardHeader><h2 className="text-sm font-bold">Recorded outcomes and overdue actions</h2></CardHeader><CardContent className="space-y-4"><div className="divide-y rounded-md border">{reviews.map((review) => <div key={review.id} className="p-4 text-xs"><div className="flex justify-between gap-3"><p className="font-semibold">{review.risk.reference} · {formatEnum(review.outcome ?? "PENDING")}</p><p className="text-muted-foreground">{review.reviewer.name}</p></div><p className="mt-1 text-muted-foreground">Scheduled {formatDate(review.scheduledFor)}{review.reassessmentRequested ? " · Reassessment requested" : ""}</p><p className="mt-2">{review.notes}</p></div>)}{!reviews.length && <p className="p-5 text-xs text-muted-foreground">No review outcomes recorded.</p>}</div>{actions.length > 0 && <div><p className="mb-2 text-xs font-bold uppercase text-destructive">Overdue action queue</p><div className="divide-y rounded-md border border-destructive/30">{actions.map((action) => <div key={action.id} className="flex justify-between gap-3 p-4 text-xs"><div><p className="font-semibold">{action.title}</p><p className="mt-1 text-muted-foreground">{action.treatmentPlan.risk.reference} · owner {action.owner.name}</p></div><p className="text-destructive">Due {formatDate(action.dueDate)}</p></div>)}</div></div>}</CardContent></Card></div></div></>;
}