import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { AssessmentDecisionForm } from "@/components/lifecycle-forms";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { requireSession } from "@/lib/authz";
import { db } from "@/lib/db";
import { formatDate, formatEnum } from "@/lib/utils";
import { uiCapabilities } from "@/lib/ui-capabilities";

export default async function AssessmentDetail({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireSession(); const { id } = await params;
  const capabilities = uiCapabilities(session.user.role);
  const assessment = await db.assessment.findFirst({ where: { id, tenantId: session.user.tenantId }, include: { risk: { select: { id: true, reference: true, title: true } }, author: { select: { id: true, name: true } }, decidedBy: { select: { name: true } } } });
  if (!assessment) notFound();
  return <><PageHeader eyebrow="Assessment detail" title={`${assessment.risk.reference} · ${formatEnum(assessment.type)}`} description="Review the immutable scoring context, rationale, decision trail, and available next transition." action={<Link href="/app/assessments" className="text-sm font-semibold text-primary">Back to register</Link>}/><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-bold">{assessment.risk.title}</h2><p className="mt-1 text-xs text-muted-foreground">Revision {assessment.revision} · created {formatDate(assessment.createdAt)}</p></div><Badge>{formatEnum(assessment.status)}</Badge></div></CardHeader><CardContent className="space-y-5"><div className="grid grid-cols-3 gap-3 text-center text-sm"><div className="rounded-md bg-muted p-4"><p className="text-xs text-muted-foreground">Likelihood</p><p className="mt-1 text-2xl font-bold">{assessment.likelihood}</p></div><div className="rounded-md bg-muted p-4"><p className="text-xs text-muted-foreground">Impact</p><p className="mt-1 text-2xl font-bold">{assessment.impact}</p></div><div className="rounded-md bg-primary/10 p-4"><p className="text-xs text-muted-foreground">Score</p><p className="mt-1 text-2xl font-bold text-primary">{assessment.score}</p></div></div><div><p className="text-xs font-bold uppercase text-muted-foreground">Rationale</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{assessment.rationale}</p></div><div className="grid gap-2 border-t pt-4 text-xs text-muted-foreground"><p>Assessor: <strong className="text-foreground">{assessment.author.name}</strong></p>{assessment.submittedAt && <p>Submitted: <strong className="text-foreground">{formatDate(assessment.submittedAt)}</strong></p>}{assessment.decidedBy && <p>Decision by: <strong className="text-foreground">{assessment.decidedBy.name}</strong> on {assessment.decidedAt && formatDate(assessment.decidedAt)}</p>}{assessment.decisionReason && <p>Decision rationale: <strong className="text-foreground">{assessment.decisionReason}</strong></p>}</div></CardContent></Card><Card><CardHeader><h2 className="text-sm font-bold">Workflow controls</h2><p className="mt-1 text-xs text-muted-foreground">Approval is separated from authorship by a server-side guard.</p></CardHeader><CardContent><AssessmentDecisionForm assessmentId={assessment.id} status={assessment.status} canSubmit={capabilities["risk:update"]} canDecide={capabilities["assessment:approve"]}/></CardContent></Card></div></>;
}