"use server";
import { revalidatePath } from "next/cache";
import { AssessmentStatus, ApprovalStatus, RiskStatus, type Prisma } from "@prisma/client";
import { z } from "zod";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/authz";
import { appendAuditEvent } from "@/lib/audit";
import { canTransition } from "@/lib/risk-lifecycle";
import { isAppetiteResolution, isValidControlEffectiveness, isValidControlImplementation, requiresApprovedInherentAssessment } from "@/lib/phase2-policy";

const text = z.string().trim().min(3).max(5000);
const id = z.string().cuid();
const refresh = (riskId?: string) => { revalidatePath("/app/governance"); if (riskId) revalidatePath(`/app/risks/${riskId}`); };

export async function createAssessment(input: unknown) {
  const session = await requirePermission("risk:update"); const parsed = z.object({ riskId:id, type:z.enum(["INHERENT","RESIDUAL"]), likelihood:z.coerce.number().int().min(1).max(5), impact:z.coerce.number().int().min(1).max(5), rationale:text }).safeParse(input); if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Invalid assessment."};
  const risk=await db.risk.findFirst({where:{id:parsed.data.riskId,tenantId:session.user.tenantId,deletedAt:null},select:{id:true}});if(!risk)return{error:"Risk not found."};
  const hasApprovedInherent = parsed.data.type === "INHERENT" || Boolean(await db.assessment.findFirst({where:{riskId:risk.id,tenantId:session.user.tenantId,type:"INHERENT",status:"APPROVED"},select:{id:true}}));
  if (!requiresApprovedInherentAssessment(parsed.data.type, hasApprovedInherent)) return { error: "Approve an inherent assessment before creating a residual assessment." };
  const assessment=await db.$transaction(async(tx:Prisma.TransactionClient)=>{const latest=await tx.assessment.findFirst({where:{riskId:risk.id,type:parsed.data.type},orderBy:{revision:"desc"}});return tx.assessment.create({data:{...parsed.data,tenantId:session.user.tenantId,revision:(latest?.revision??0)+1,score:parsed.data.likelihood*parsed.data.impact,authorId:session.user.id}})});refresh(risk.id);return{success:true,id:assessment.id};
}
export async function submitAssessment(assessmentId:string){const session=await requirePermission("risk:update");const result=await db.assessment.updateMany({where:{id:assessmentId,tenantId:session.user.tenantId,status:{in:["DRAFT","REJECTED"]}},data:{status:"SUBMITTED",submittedAt:new Date()}});if(result.count!==1)return{error:"Only a draft or rejected assessment can be submitted."};refresh();return{success:true};}
export async function decideAssessment(assessmentId:string,decision:"APPROVED"|"REJECTED",reason:string){const session=await requirePermission("assessment:approve");const rationale=text.safeParse(reason);if(!rationale.success)return{error:"A decision rationale is required."};const current=await db.assessment.findFirst({where:{id:assessmentId,tenantId:session.user.tenantId,status:"SUBMITTED"},include:{risk:true}});if(!current)return{error:"Submitted assessment not found."};if(current.authorId===session.user.id)return{error:"The assessment author cannot approve their own assessment."};await db.$transaction(async(tx:Prisma.TransactionClient)=>{await tx.assessment.update({where:{id:current.id},data:{status:decision,decidedById:session.user.id,decidedAt:new Date(),decisionReason:rationale.data}});if(decision==="APPROVED"){await tx.assessment.updateMany({where:{riskId:current.riskId,type:current.type,status:"APPROVED",id:{not:current.id}},data:{status:"SUPERSEDED"}});await tx.risk.update({where:{id:current.riskId},data:current.type==="INHERENT"?{inherentLikelihood:current.likelihood,inherentImpact:current.impact,inherentScore:current.score,version:{increment:1}}:{residualLikelihood:current.likelihood,residualImpact:current.impact,residualScore:current.score,version:{increment:1}}});}await appendAuditEvent(tx,{tenantId:session.user.tenantId,actorId:session.user.id,action:"UPDATE",riskId:current.riskId,entityType:"Assessment",entityId:current.id,summary:`${decision.toLowerCase()} assessment revision ${current.revision}`,changes:{reason:rationale.data}})});refresh(current.riskId);return{success:true};}
export async function transitionRisk(riskId:string,to:RiskStatus,reason:string){const session=await requirePermission("risk:update");const risk=await db.risk.findFirst({where:{id:riskId,tenantId:session.user.tenantId,deletedAt:null}});if(!risk||!canTransition(risk.status,to))return{error:"This lifecycle transition is not allowed."};if(["ACCEPTED","CLOSED"].includes(to)&&reason.trim().length<10)return{error:"A decision rationale of at least 10 characters is required."};await db.$transaction(async(tx:Prisma.TransactionClient)=>{await tx.risk.update({where:{id:risk.id},data:{status:to,version:{increment:1}}});await appendAuditEvent(tx,{tenantId:session.user.tenantId,actorId:session.user.id,action:"UPDATE",riskId:risk.id,entityType:"Risk",entityId:risk.id,summary:`Transitioned ${risk.reference} from ${risk.status} to ${to}`,changes:{reason}})});refresh(risk.id);return{success:true};}
export async function createTreatment(input:unknown){const session=await requirePermission("treatment:manage");const p=z.object({riskId:id,strategy:z.enum(["ACCEPT","MITIGATE","TRANSFER","AVOID"]),summary:text,targetDate:z.coerce.date()}).safeParse(input);if(!p.success)return{error:p.error.issues[0]?.message??"Invalid treatment."};const risk=await db.risk.findFirst({where:{id:p.data.riskId,tenantId:session.user.tenantId,deletedAt:null}});if(!risk)return{error:"Risk not found."};const plan=await db.treatmentPlan.create({data:{...p.data,tenantId:session.user.tenantId,createdById:session.user.id}});refresh(risk.id);return{success:true,id:plan.id};}
export async function decideTreatment(planId:string,status:"APPROVED"|"REJECTED",rationale:string){const session=await requirePermission("treatment:approve");const plan=await db.treatmentPlan.findFirst({where:{id:planId,tenantId:session.user.tenantId,status:"PENDING"},include:{risk:true}});if(!plan||rationale.trim().length<10)return{error:"A pending plan and decision rationale are required."};if(plan.createdById===session.user.id)return{error:"The plan creator cannot approve their own plan."};await db.$transaction(async(tx:Prisma.TransactionClient)=>{await tx.treatmentPlan.update({where:{id:plan.id},data:{status}});await tx.approvalDecision.create({data:{treatmentPlanId:plan.id,kind:plan.strategy==="ACCEPT"?"RISK_ACCEPTANCE":"TREATMENT",status,rationale,decidedById:session.user.id}});if(status==="APPROVED")await tx.risk.update({where:{id:plan.riskId},data:{treatment:plan.strategy,status:plan.strategy==="ACCEPT"?"ACCEPTED":"TREATMENT",version:{increment:1}}});await appendAuditEvent(tx,{tenantId:session.user.tenantId,actorId:session.user.id,action:"UPDATE",riskId:plan.riskId,entityType:"TreatmentPlan",entityId:plan.id,summary:`${status.toLowerCase()} ${plan.strategy.toLowerCase()} plan`,changes:{rationale}})});refresh(plan.riskId);return{success:true};}
export async function createTreatmentAction(input:unknown){const session=await requirePermission("treatment:manage");const p=z.object({treatmentPlanId:id,title:text,description:text,ownerId:id,dueDate:z.coerce.date(),priority:z.enum(["LOW","MEDIUM","HIGH","CRITICAL"])}).safeParse(input);if(!p.success)return{error:p.error.issues[0]?.message??"Invalid action."};const plan=await db.treatmentPlan.findFirst({where:{id:p.data.treatmentPlanId,tenantId:session.user.tenantId}});const owner=await db.user.findFirst({where:{id:p.data.ownerId,tenantId:session.user.tenantId}});if(!plan||!owner)return{error:"Plan or owner not found in this workspace."};const action=await db.treatmentAction.create({data:{...p.data,tenantId:session.user.tenantId}});refresh(plan.riskId);return{success:true,id:action.id};}
export async function updateTreatmentAction(actionId:string,status:"NOT_STARTED"|"IN_PROGRESS"|"BLOCKED"|"COMPLETED"|"CANCELLED"){const session=await requirePermission("treatment:manage");const action=await db.treatmentAction.findFirst({where:{id:actionId,tenantId:session.user.tenantId},include:{treatmentPlan:true}});if(!action)return{error:"Action not found."};const completedAt=status==="COMPLETED"?new Date():null;await db.$transaction(async(tx:Prisma.TransactionClient)=>{await tx.treatmentAction.update({where:{id:action.id},data:{status,completedAt}});await appendAuditEvent(tx,{tenantId:session.user.tenantId,actorId:session.user.id,action:"UPDATE",riskId:action.treatmentPlan.riskId,entityType:"TreatmentAction",entityId:action.id,summary:`Updated treatment action to ${status}`,changes:{status}})});refresh(action.treatmentPlan.riskId);return{success:true};}
export async function escalateOverdueActions(asOf=new Date()){const session=await requirePermission("treatment:manage");const result=await db.treatmentAction.updateMany({where:{tenantId:session.user.tenantId,dueDate:{lt:asOf},status:{in:["NOT_STARTED","IN_PROGRESS","BLOCKED"]}},data:{escalatedAt:asOf,escalationLevel:{increment:1}}});refresh();return{success:true,count:result.count};}
export async function upsertControlProfile(input:unknown){const session=await requirePermission("control:manage");const p=z.object({frameworkControlId:id,ownerId:id.optional(),implementationStatus:z.string().refine(isValidControlImplementation,"Invalid implementation status."),effectiveness:z.string().refine(isValidControlEffectiveness,"Invalid effectiveness."),frequency:z.string().max(80).optional(),notes:z.string().max(5000).optional()}).safeParse(input);if(!p.success)return{error:"Invalid control profile."};const control=await db.frameworkControl.findFirst({where:{id:p.data.frameworkControlId,framework:{tenantSelections:{some:{tenantId:session.user.tenantId,enabled:true}}}}});if(!control)return{error:"Control is not enabled for this workspace."};if(p.data.ownerId&&!(await db.user.findFirst({where:{id:p.data.ownerId,tenantId:session.user.tenantId},select:{id:true}})))return{error:"Control owner is not a member of this workspace."};await db.controlProfile.upsert({where:{tenantId_frameworkControlId:{tenantId:session.user.tenantId,frameworkControlId:control.id}},create:{...p.data,tenantId:session.user.tenantId},update:p.data});refresh();return{success:true};}
export async function createEvidence(input:unknown){const session=await requirePermission("evidence:manage");const p=z.object({title:text,description:z.string().max(5000).optional(),fileName:z.string().max(255).optional(),mimeType:z.string().max(120).optional(),sizeBytes:z.coerce.number().int().min(0).max(25_000_000).optional(),checksum:z.string().max(128).optional(),treatmentPlanId:id.optional(),treatmentActionId:id.optional(),controlProfileId:id.optional(),expiresAt:z.coerce.date().optional()}).safeParse(input);if(!p.success)return{error:"Invalid evidence metadata."};if(!p.data.treatmentPlanId&&!p.data.treatmentActionId&&!p.data.controlProfileId)return{error:"Evidence must be linked to a treatment plan, action, or control."};const [plan,action,control]=await Promise.all([p.data.treatmentPlanId?db.treatmentPlan.findFirst({where:{id:p.data.treatmentPlanId,tenantId:session.user.tenantId},select:{id:true}}):null,p.data.treatmentActionId?db.treatmentAction.findFirst({where:{id:p.data.treatmentActionId,tenantId:session.user.tenantId},select:{id:true}}):null,p.data.controlProfileId?db.controlProfile.findFirst({where:{id:p.data.controlProfileId,tenantId:session.user.tenantId},select:{id:true}}):null]);if((p.data.treatmentPlanId&&!plan)||(p.data.treatmentActionId&&!action)||(p.data.controlProfileId&&!control))return{error:"Evidence links must belong to this workspace."};await db.evidence.create({data:{...p.data,tenantId:session.user.tenantId,uploadedById:session.user.id}});refresh();return{success:true};}
export async function createAppetiteStatement(input:unknown){const session=await requirePermission("appetite:manage");const p=z.object({name:text,category:z.enum(["CYBERSECURITY","COMPLIANCE","OPERATIONAL","STRATEGIC","FINANCIAL","PEOPLE","THIRD_PARTY","RESILIENCE","PRIVACY"]).optional(),maximumScore:z.coerce.number().int().min(1).max(25),rationale:text,effectiveFrom:z.coerce.date()}).safeParse(input);if(!p.success)return{error:"Invalid appetite statement."};await db.appetiteStatement.create({data:{...p.data,tenantId:session.user.tenantId}});refresh();return{success:true};}
export async function evaluateAppetite(){const session=await requirePermission("appetite:manage");const [risks,statements]=await Promise.all([db.risk.findMany({where:{tenantId:session.user.tenantId,deletedAt:null,residualScore:{not:null}}}),db.appetiteStatement.findMany({where:{tenantId:session.user.tenantId,active:true}})]);let count=0;for(const risk of risks){for(const statement of statements.filter(s=>!s.category||s.category===risk.category)){if((risk.residualScore??0)>statement.maximumScore){await db.appetiteBreach.upsert({where:{riskId_appetiteStatementId_status:{riskId:risk.id,appetiteStatementId:statement.id,status:"OPEN"}},create:{tenantId:session.user.tenantId,riskId:risk.id,appetiteStatementId:statement.id,observedScore:risk.residualScore!,ownerId:risk.ownerId},update:{observedScore:risk.residualScore!}});count++;}}}refresh();return{success:true,count};}
export async function resolveAppetiteBreach(breachId:string,status:"ACKNOWLEDGED"|"TREATING"|"ACCEPTED"|"RESOLVED",response:string){const session=await requirePermission("appetite:manage");if(!isAppetiteResolution(status)||response.trim().length<10)return{error:"A resolution status and rationale of at least 10 characters are required."};const breach=await db.appetiteBreach.findFirst({where:{id:breachId,tenantId:session.user.tenantId}});if(!breach)return{error:"Appetite breach not found."};await db.$transaction(async(tx:Prisma.TransactionClient)=>{await tx.appetiteBreach.update({where:{id:breach.id},data:{status,response,acknowledgedAt:status==="ACKNOWLEDGED"?new Date():breach.acknowledgedAt,resolvedAt:status==="RESOLVED"?new Date():null}});await appendAuditEvent(tx,{tenantId:session.user.tenantId,actorId:session.user.id,action:"UPDATE",riskId:breach.riskId,entityType:"AppetiteBreach",entityId:breach.id,summary:`Resolved appetite breach as ${status}`,changes:{status,response}})});refresh(breach.riskId);return{success:true};}
export async function createTaxonomyItem(input:unknown){const session=await requirePermission("taxonomy:manage");const p=z.object({type:z.enum(["RISK_CATEGORY","BUSINESS_UNIT","OBJECTIVE","RISK_SOURCE","REGULATORY_DOMAIN","TAG"]),name:text,description:z.string().max(1000).optional()}).safeParse(input);if(!p.success)return{error:"Invalid taxonomy item."};await db.taxonomyItem.create({data:{...p.data,tenantId:session.user.tenantId}});refresh();return{success:true};}