import Link from "next/link";
import { notFound } from "next/navigation";
import { Calendar, CheckSquare, Edit3, MessageSquare, UserRound } from "lucide-react";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/authz";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { RiskBadge } from "@/components/risk-badge";
import { formatDate, formatEnum } from "@/lib/utils";
export default async function RiskDetail({ params }: { params: Promise<{ id: string }> }) { const session = await requireSession(); const { id } = await params; const risk = await db.risk.findFirst({ where: { id, tenantId: session.user.tenantId, deletedAt: null }, include: { owner: true, auditEvents: { include: { actor: true }, orderBy: { createdAt: "desc" } } } }); if (!risk) notFound(); return <><div className="mb-7 flex flex-col justify-between gap-4 border-b pb-7 sm:flex-row sm:items-end"><div><Link href="/app/risks" className="text-xs font-semibold text-primary">← Risk register</Link><p className="mt-6 text-[10px] font-bold uppercase tracking-[.16em] text-muted-foreground">{risk.reference}</p><h1 className="mt-2 max-w-4xl font-display text-3xl sm:text-4xl">{risk.title}</h1><div className="mt-4 flex flex-wrap gap-2"><Badge>{formatEnum(risk.category)}</Badge><Badge>{formatEnum(risk.status)}</Badge><Badge>{formatEnum(risk.treatment)}</Badge></div></div><Button asChild variant="outline"><Link href={`/app/risks/${id}/edit`}><Edit3 className="size-4"/>Edit risk</Link></Button></div><div className="grid items-start gap-5 xl:grid-cols-[1fr_360px]"><div className="space-y-5"><Card><CardHeader><h2 className="text-sm font-bold">Risk description</h2></CardHeader><CardContent><p className="text-sm leading-7 text-muted-foreground">{risk.description}</p></CardContent></Card><Card><CardHeader><h2 className="text-sm font-bold">Change history</h2><p className="mt-1 text-xs text-muted-foreground">Material events recorded for this risk.</p></CardHeader><CardContent>{risk.auditEvents.map(event => <div key={event.id} className="relative border-l pb-6 pl-6 last:pb-0"><span className="absolute -left-1.5 top-0 size-3 rounded-full border-2 border-card bg-primary"/><p className="text-sm font-semibold">{event.summary}</p><p className="mt-1 text-xs text-muted-foreground">{event.actor.name} · {formatDate(event.createdAt)}</p></div>)}</CardContent></Card><div className="grid gap-5 sm:grid-cols-2"><Placeholder icon={MessageSquare} title="Comments" text="Discussion and mentions will appear here."/><Placeholder icon={CheckSquare} title="Linked actions" text="Treatment actions and due dates will appear here."/></div></div><aside className="space-y-5"><Card><CardHeader><h2 className="text-sm font-bold">Current assessment</h2></CardHeader><CardContent className="space-y-5"><Assessment label="Inherent exposure" likelihood={risk.inherentLikelihood} impact={risk.inherentImpact} score={risk.inherentScore}/><div className="border-t"/><Assessment label="Residual exposure" likelihood={risk.residualLikelihood} impact={risk.residualImpact} score={risk.residualScore}/></CardContent></Card><Card><CardContent className="space-y-4 pt-5"><Meta icon={UserRound} label="Risk owner" value={risk.owner.name}/><Meta icon={Calendar} label="Next review" value={formatDate(risk.nextReviewDate)}/></CardContent></Card></aside></div></>; }
function Assessment({ label, likelihood, impact, score }: { label: string; likelihood: number | null; impact: number | null; score: number | null }) { return <div><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold">{label}</p><RiskBadge score={score}/></div><div className="grid grid-cols-2 gap-2 text-xs text-muted-foreground"><p className="rounded-md bg-muted p-3">Likelihood <strong className="float-right text-foreground">{likelihood ?? "-"}</strong></p><p className="rounded-md bg-muted p-3">Impact <strong className="float-right text-foreground">{impact ?? "-"}</strong></p></div></div>; }
function Meta({ icon: Icon, label, value }: { icon: typeof Calendar; label: string; value: string }) { return <div className="flex gap-3"><Icon className="mt-0.5 size-4 text-primary"/><div><p className="text-[10px] uppercase tracking-[.1em] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div></div>; }
function Placeholder({ icon: Icon, title, text }: { icon: typeof Calendar; title: string; text: string }) { return <Card><CardContent className="flex gap-4 pt-5"><div className="grid size-9 shrink-0 place-items-center rounded-md bg-muted"><Icon className="size-4 text-muted-foreground"/></div><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{text}</p></div></CardContent></Card>; }