import Link from "next/link";
import { ArrowRight, BarChart3, BookOpenCheck, BrainCircuit, Building2, Check, ChevronRight, CircleCheck, FileCheck2, Gauge, Globe2, Menu, Radar, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Brand } from "@/components/brand";
import { PricingSection } from "@/components/pricing-section";

const features = [
  { icon: BookOpenCheck, title: "Risk Register", text: "Capture accountable risks, treatments, owners, reviews, and evidence in one living record." },
  { icon: Gauge, title: "Assessment & Scoring", text: "Apply consistent likelihood and impact measures, then compare inherent and residual exposure." },
  { icon: FileCheck2, title: "Compliance Linkage", text: "Connect each risk to relevant obligations, official excerpts, frameworks, and jurisdictions." },
  { icon: Sparkles, title: "Board-Language Translator", text: "Turn technical findings into clear business exposure, decision context, and management action." },
  { icon: Globe2, title: "Industry Coverage", text: "Start with practical healthcare and fintech libraries plus worldwide compliance references." },
  { icon: Radar, title: "Emerging Risk", text: "Monitor weak signals, define indicators, and promote validated hypotheses into the formal register." },
];
const faqs = [
  ["Can I start without a risk specialist?", "Yes. Guided fields, consistent scoring, practical language, and seeded examples help operational owners build a credible register while keeping human accountability clear."],
  ["Is each organisation's data isolated?", "Yes. Every authenticated query and mutation derives the tenant from the active server session and membership. Users cannot select or supply a different tenant."],
  ["Does BeyondBeams replace professional advice?", "No. BeyondBeams structures evidence and supports judgement. Compliance references and AI-assisted language remain reviewable inputs, not legal, regulatory, or professional advice."],
  ["Can read-only stakeholders participate?", "Yes. Viewer and Auditor roles can inspect tenant information without mutation rights. Owners and Risk Managers control invitations and role assignment."],
  ["What happens after the free plan?", "Your data remains yours. Upgrade when you need more capacity or team features; transparent plan prices are shown here without requiring a sales call."],
];

function Heatmap() { const markers = new Map([["4-4","RSK-008"],["3-5","RSK-003"],["2-3","RSK-005"]]); return <div className="relative border border-white/10 bg-[#071c2f] p-4 shadow-2xl shadow-black/30 sm:p-6"><div className="mb-5 flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-[10px] font-bold uppercase text-slate-500">Portfolio exposure</p><h2 className="mt-1 text-sm font-bold">Residual risk field</h2></div><div className="flex items-center gap-2 text-[10px] text-primary"><span className="size-1.5 rounded-full bg-primary shadow-[0_0_10px_#00A896]"/>Live workspace</div></div><div className="grid grid-cols-[auto_1fr] gap-3"><span className="self-center text-[9px] font-bold uppercase text-slate-600 [writing-mode:vertical-rl] rotate-180">Impact</span><div className="grid grid-cols-5 gap-1.5">{[5,4,3,2,1].flatMap(impact=>[1,2,3,4,5].map(likelihood=>{const score=impact*likelihood;const marker=markers.get(`${impact}-${likelihood}`);return <div key={`${impact}-${likelihood}`} className={`relative aspect-square border ${score>=15?"border-red-300/25 bg-red-400/15":score>=7?"border-amber-200/20 bg-amber-300/10":"border-primary/20 bg-primary/[.08]"}`}>{marker&&<span className="absolute inset-1 grid place-items-center bg-white text-[7px] font-extrabold text-[#0A2540] shadow-lg sm:text-[8px]">{marker}</span>}</div>}) )}<p className="col-span-5 pt-1 text-center text-[9px] font-bold uppercase text-slate-600">Likelihood</p></div></div><div className="mt-5 grid grid-cols-3 divide-x divide-white/10 border-t border-white/10 pt-5"><Metric value="08" label="Open risks"/><Metric value="03" label="Actions due"/><Metric value="71%" label="Coverage" accent/></div></div> }
function Metric({value,label,accent}:{value:string;label:string;accent?:boolean}){return <div className="px-2 first:pl-0"><p className={`font-display text-2xl ${accent?"text-primary":"text-white"}`}>{value}</p><p className="mt-1 text-[9px] uppercase text-slate-500">{label}</p></div>}

export default function LandingPage(){return <main className="overflow-hidden bg-[#0A2540] text-white">
  <header className="sticky top-0 z-50 border-b border-white/10 bg-[#0A2540]/95 backdrop-blur-xl"><div className="landing-section flex h-16 items-center"><Link href="/" aria-label="BeyondBeams home" className="landing-link"><Brand/></Link><nav className="ml-auto hidden items-center gap-7 md:flex" aria-label="Main navigation">{[["Features","#features"],["Pricing","#pricing"],["Resources","#resources"],["About","#about"]].map(([label,href])=><Link className="landing-link text-xs font-semibold text-slate-300" href={href} key={label}>{label}</Link>)}<Link className="landing-link text-xs font-semibold text-white" href="/login">Login</Link><Link className="landing-button min-h-9 bg-[#00A896] px-4 text-[#052b31] hover:-translate-y-0.5 hover:bg-teal-300" href="/register">Start Free</Link></nav><details className="group relative ml-auto md:hidden"><summary className="grid size-10 cursor-pointer list-none place-items-center rounded-md border border-white/15 focus-visible:ring-2 focus-visible:ring-primary"><Menu className="size-5"/></summary><nav className="absolute right-0 top-12 w-56 border border-white/10 bg-[#071c2f] p-2 shadow-2xl">{[["Features","#features"],["Pricing","#pricing"],["Resources","#resources"],["About","#about"],["Login","/login"],["Start Free","/register"]].map(([label,href])=><Link className="block rounded-sm px-4 py-3 text-sm text-slate-200 hover:bg-white/[.06] hover:text-white" href={href} key={label}>{label}</Link>)}</nav></details></div></header>

  <section className="landing-section grid min-h-[calc(100vh-4rem)] items-center gap-14 py-16 lg:grid-cols-[1.04fr_.96fr] lg:py-24"><div><div className="mb-7 inline-flex items-center gap-2 border border-primary/30 bg-primary/10 px-3 py-2 text-[10px] font-bold uppercase text-teal-100"><ShieldCheck className="size-3.5 text-primary"/>Practical GRC for accountable teams</div><h1 className="max-w-3xl text-balance font-display text-5xl leading-[1.02] sm:text-7xl lg:text-[78px]">See risk clearly.<br/><span className="italic text-teal-200">Move with confidence.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">BeyondBeams turns fragmented risk, compliance, and assurance work into one decision-ready operating picture, without the cost and complexity of enterprise GRC.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="landing-button bg-[#00A896] text-[#052b31] shadow-lg shadow-teal-950/30 hover:-translate-y-0.5 hover:bg-teal-300">Start Free <ArrowRight className="size-4"/></Link><Link href="#how" className="landing-button border border-white/20 text-white hover:border-white/40 hover:bg-white/[.06]">See how it works</Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-400">{["No credit card", "Tenant-isolated", "Setup in minutes"].map(item=><span className="flex items-center gap-2" key={item}><CircleCheck className="size-3.5 text-primary"/>{item}</span>)}</div></div><div className="relative lg:pl-8"><div className="absolute -inset-10 border-l border-t border-primary/10" aria-hidden/><Heatmap/><div className="relative -mt-4 ml-auto mr-4 flex w-[82%] items-center gap-3 border border-white/10 bg-[#0d2d49] p-3 shadow-xl sm:w-[72%]"><BrainCircuit className="size-5 shrink-0 text-primary"/><div><p className="text-[10px] font-bold">Board perspective prepared</p><p className="mt-0.5 text-[9px] text-slate-400">Technical exposure translated for executive review</p></div><Check className="ml-auto size-4 text-primary"/></div></div></section>

  <section id="about" className="border-y border-white/10 bg-[#071c2f]"><div className="landing-section grid gap-12 py-20 lg:grid-cols-2 lg:py-28"><div><p className="text-xs font-bold uppercase text-primary">The operating gap</p><h2 className="mt-4 text-balance font-display text-4xl sm:text-5xl">Risk work is everywhere.<br/>Accountability is nowhere.</h2></div><div className="grid gap-6 sm:grid-cols-2"><div className="border-l border-red-300/40 pl-5"><p className="text-sm font-bold">Before</p><p className="mt-3 text-sm leading-7 text-slate-400">Scattered spreadsheets, inconsistent scores, stale reviews, and compliance context found too late.</p></div><div className="border-l border-primary pl-5"><p className="text-sm font-bold text-teal-100">With BeyondBeams</p><p className="mt-3 text-sm leading-7 text-slate-400">A shared, accountable system connecting exposure, obligations, decisions, evidence, and communication.</p></div></div></div></section>

  <section id="features" className="landing-section py-20 lg:py-28"><div className="max-w-2xl"><p className="text-xs font-bold uppercase text-primary">A complete risk workspace</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">From signal to board decision.</h2><p className="mt-5 leading-7 text-slate-400">Six connected capabilities give growing organisations a clear operating rhythm for governance.</p></div><div className="mt-12 grid border-l border-t border-white/10 sm:grid-cols-2 lg:grid-cols-3">{features.map(({icon:Icon,title,text},index)=><article className="group min-h-64 border-b border-r border-white/10 p-7 transition-colors hover:bg-white/[.035]" key={title}><span className="grid size-10 place-items-center border border-primary/30 bg-primary/10 text-primary transition-transform group-hover:-translate-y-1"><Icon className="size-5"/></span><p className="mt-8 text-[10px] font-bold text-slate-600">0{index+1}</p><h3 className="mt-2 text-base font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></section>

  <section id="how" className="border-y border-white/10 bg-[#071c2f]"><div className="landing-section py-20 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase text-primary">How it works</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Clarity in three moves.</h2></div><ol className="grid gap-px bg-white/10 sm:grid-cols-3">{[["01","Capture","Record the uncertain event, accountable owner, and business context."],["02","Assess","Score exposure and connect relevant controls and obligations."],["03","Act","Treat, monitor, evidence, and communicate the decision clearly."]].map(([number,title,text])=><li className="bg-[#071c2f] p-6" key={number}><span className="font-display text-3xl text-primary">{number}</span><h3 className="mt-8 text-sm font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></li>)}</ol></div></div></section>

  <PricingSection />

  <section id="resources" className="border-y border-white/10 bg-[#071c2f]"><div className="landing-section grid gap-12 py-20 lg:grid-cols-[1fr_1.1fr] lg:py-24"><div><p className="text-xs font-bold uppercase text-primary">Trusted operating principles</p><h2 className="mt-4 font-display text-4xl">Built for scrutiny,<br/>not theatre.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-slate-400">Secure tenant boundaries, explicit roles, auditable activity, human-reviewed assistance, and linked source context are part of the workflow.</p></div><div className="grid grid-cols-2 gap-px bg-white/10">{[[Building2,"Tenant isolation"],[Users,"Five clear roles"],[ShieldCheck,"Auditable actions"],[BarChart3,"Consistent scoring"]].map(([Icon,label])=>{const I=Icon as typeof Building2;return <div className="bg-[#071c2f] p-5 sm:p-7" key={String(label)}><I className="size-5 text-primary"/><p className="mt-5 text-xs font-bold">{String(label)}</p></div>})}</div></div></section>

  <section className="landing-section grid gap-14 py-20 lg:grid-cols-2 lg:py-28"><div><p className="text-xs font-bold uppercase text-primary">Common questions</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Answers before you begin.</h2></div><div className="divide-y divide-white/10 border-y border-white/10">{faqs.map(([question,answer])=><details className="group py-1" key={question}><summary className="flex cursor-pointer list-none items-center gap-4 py-5 text-sm font-bold focus-visible:outline-none focus-visible:text-primary">{question}<ChevronRight className="ml-auto size-4 shrink-0 text-primary transition-transform group-open:rotate-90"/></summary><p className="pb-6 pr-8 text-sm leading-7 text-slate-400">{answer}</p></details>)}</div></section>

  <section className="bg-[#00A896] text-[#052b31]"><div className="landing-section flex flex-col gap-7 py-14 lg:flex-row lg:items-center"><div><p className="text-xs font-bold uppercase">Make risk useful</p><h2 className="mt-2 font-display text-4xl">Give every risk a clear next move.</h2></div><div className="flex flex-col gap-3 sm:flex-row lg:ml-auto"><Link href="/register" className="landing-button bg-[#0A2540] text-white hover:bg-[#071c2f]">Start Free <ArrowRight className="size-4"/></Link><Link href="mailto:demo@beyondbeams.com" className="landing-button border border-[#0A2540]/40 hover:bg-white/20">Talk to us</Link></div></div></section>

  <footer className="bg-[#061827]"><div className="landing-section py-14"><div className="grid gap-10 border-b border-white/10 pb-12 lg:grid-cols-[1.5fr_repeat(4,1fr)]"><div><Brand/><p className="mt-5 max-w-xs text-xs leading-6 text-slate-500">Practical risk intelligence for accountable organisations.</p></div>{[["Product",["Features","Pricing","Security"]],["Resources",["Risk library","Compliance guide","Help centre"]],["Company",["About","Contact","Careers"]],["Legal",["Privacy","Terms","AI usage"]]].map(([heading,items])=><div key={String(heading)}><p className="text-xs font-bold">{String(heading)}</p><ul className="mt-4 space-y-3">{(items as string[]).map(item=><li key={item}><Link href={item==="Features"?"#features":item==="Pricing"?"#pricing":"#resources"} className="landing-link text-xs text-slate-500 hover:text-white">{item}</Link></li>)}</ul></div>)}</div><div className="grid gap-8 border-b border-white/10 py-10 lg:grid-cols-[1fr_1.2fr]"><div><p className="text-xs font-bold">Useful risk thinking, occasionally.</p><form className="mt-4 flex max-w-sm" action="mailto:hello@beyondbeams.com"><label htmlFor="newsletter" className="sr-only">Work email for newsletter</label><input id="newsletter" name="email" type="email" required placeholder="Work email" className="min-w-0 flex-1 border border-white/15 bg-white/[.04] px-3 text-xs outline-none focus:border-primary"/><button className="grid size-11 shrink-0 place-items-center bg-[#00A896] text-[#052b31] transition-colors hover:bg-teal-300" aria-label="Subscribe"><ArrowRight className="size-4"/></button></form></div><div><p className="flex items-center gap-2 text-xs font-bold text-teal-100"><BrainCircuit className="size-4 text-primary"/>Respectful AI use at work</p><p className="mt-3 text-xs leading-6 text-slate-500">BeyondBeams uses assistance to clarify language and surface relevant context. People remain accountable for decisions. Tenant data is protected, outputs stay reviewable, and AI does not replace professional judgement or workplace dignity.</p></div></div><div className="flex flex-col gap-3 pt-7 text-[10px] text-slate-600 sm:flex-row sm:items-center"><span>© 2026 BeyondBeams GRC. All rights reserved.</span><span className="sm:ml-auto">Risk intelligence, clearly aligned.</span></div></div></footer>
</main>}