"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";
import { ArrowRight, LoaderCircle } from "lucide-react";
import { acceptInvitation, registerAccount, requestMagicLink, requestPasswordReset, resetPassword } from "@/app/actions/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { TurnstileWidget } from "@/components/turnstile-widget";
import { turnstileSiteKey } from "@/lib/turnstile";

const fieldClass = "border-white/10 bg-white/[.06] text-white placeholder:text-slate-600 focus:border-primary";
function Message({ error, message }: { error?: string; message?: string }) { return error ? <p role="alert" className="rounded-md border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p> : message ? <p role="status" className="rounded-md border border-primary/20 bg-primary/10 p-3 text-sm text-teal-100">{message}</p> : null; }

export function RegisterForm() {
  const router = useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const input={name:String(data.get("name")),email:String(data.get("email")),organisation:String(data.get("organisation")),password:String(data.get("password")),turnstileToken:String(data.get("cf-turnstile-response") ?? "")};const result=await registerAccount(input);if(result.error){setError(result.error);setBusy(false);return;}const login=await signIn("credentials",{email:input.email,password:input.password,redirect:false});if(login?.error){router.push("/login?registered=1");return;}router.push("/app");router.refresh();}
  return <form onSubmit={submit} className="space-y-4">{[["name","Your name","Maya Chen","text"],["email","Work email","you@company.com","email"],["organisation","Organisation","Acme Health","text"],["password","Password","10+ characters","password"]].map(([name,label,placeholder,type])=><div className="space-y-2" key={name}><Label htmlFor={name} className="text-xs text-slate-300">{label}</Label><Input id={name} name={name} placeholder={placeholder} type={type} required autoComplete={name==="password"?"new-password":name} className={fieldClass}/></div>)}<TurnstileWidget siteKey={turnstileSiteKey()} action="register"/><Message error={error}/><Button disabled={busy} className="h-11 w-full">{busy?<LoaderCircle className="size-4 animate-spin"/>:<ArrowRight className="size-4"/>}Create my workspace</Button><p className="text-center text-xs text-slate-500">Already have an account? <Link href="/login" className="text-primary hover:underline">Sign in</Link></p></form>;
}

export function MagicLinkForm(){const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const result=await requestMagicLink(String(data.get("email")),String(data.get("cf-turnstile-response") ?? ""));if(result.error)setError(result.error);else setMessage(result.message??"");setBusy(false);}return <form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label htmlFor="magic-email" className="text-xs text-slate-300">Work email</Label><Input id="magic-email" name="email" type="email" required autoComplete="email" placeholder="you@company.com" className={fieldClass}/></div><TurnstileWidget siteKey={turnstileSiteKey()} action="magic-link"/><Message error={error} message={message}/><Button disabled={busy} className="h-11 w-full">{busy&&<LoaderCircle className="size-4 animate-spin"/>}Email me a secure link</Button><p className="text-center text-xs text-slate-500"><Link href="/login" className="text-primary hover:underline">Use a password instead</Link></p></form>}

export function AcceptInviteForm({token,email,tenant,role}:{token:string;email:string;tenant:string;role:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const password=String(data.get("password"));const result=await acceptInvitation({token,name:String(data.get("name")),password});if(result.error){setError(result.error);setBusy(false);return;}const login=await signIn("credentials",{email,password,redirect:false});if(login?.error){router.push("/login?invited=1");return;}router.push("/app");router.refresh();}return <form onSubmit={submit} className="space-y-4"><div className="rounded-md border border-primary/20 bg-primary/10 p-4 text-sm text-teal-50"><strong>{email}</strong><br/><span className="text-slate-400">Joining {tenant} as {role}</span></div><div className="space-y-2"><Label htmlFor="name" className="text-xs text-slate-300">Your name</Label><Input id="name" name="name" required autoComplete="name" className={fieldClass}/></div><div className="space-y-2"><Label htmlFor="password" className="text-xs text-slate-300">Create password</Label><Input id="password" name="password" type="password" minLength={10} required autoComplete="new-password" className={fieldClass}/></div><Message error={error}/><Button disabled={busy} className="h-11 w-full">{busy&&<LoaderCircle className="size-4 animate-spin"/>}Accept and join workspace</Button></form>}

export function MagicLinkExchange({email,token}:{email:string;token:string}){const router=useRouter();const[error,setError]=useState("");useEffect(()=>{let active=true;signIn("magic-link",{email,token,redirect:false}).then((result)=>{if(!active)return;if(result?.error)setError("This sign-in link is invalid or has expired.");else{router.replace("/app");router.refresh();}});return()=>{active=false}},[email,token,router]);return <div className="text-center"><LoaderCircle className="mx-auto size-7 animate-spin text-primary"/><p className="mt-4 text-sm text-slate-300">Verifying your secure sign-in link…</p>{error&&<div className="mt-5"><Message error={error}/><Link href="/magic-link" className="mt-4 inline-block text-sm text-primary">Request another link</Link></div>}</div>}

export function ResetPasswordForm({ email, token }: { email: string; token: string }) { const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); const result = await resetPassword({ email, token, password: String(data.get("password")) }); if (result.error) setError(result.error); else { setMessage("Password changed. Existing sessions have been invalidated."); setTimeout(() => router.push("/login"), 1200); } setBusy(false); } return <form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label htmlFor="reset-email" className="text-xs text-slate-300">Email</Label><Input id="reset-email" value={email} readOnly className={fieldClass}/></div><div className="space-y-2"><Label htmlFor="reset-password" className="text-xs text-slate-300">New password</Label><Input id="reset-password" name="password" type="password" minLength={10} required autoComplete="new-password" className={fieldClass}/></div><Message error={error} message={message}/><Button disabled={busy || !email || !token} className="h-11 w-full">{busy&&<LoaderCircle className="size-4 animate-spin"/>}Set new password</Button></form>; }

export function RequestPasswordResetForm() { const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); const result = await requestPasswordReset(String(data.get("email")), String(data.get("cf-turnstile-response") ?? "")); setMessage(result.message ?? "If an account exists, a reset link has been sent."); setBusy(false); } return <form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label htmlFor="reset-request-email" className="text-xs text-slate-300">Work email</Label><Input id="reset-request-email" name="email" type="email" required autoComplete="email" className={fieldClass}/></div><TurnstileWidget siteKey={turnstileSiteKey()} action="password-reset"/><Message message={message}/><Button disabled={busy} className="h-11 w-full">{busy&&<LoaderCircle className="size-4 animate-spin"/>}Email reset link</Button><p className="text-center text-xs text-slate-500"><Link href="/login" className="text-primary hover:underline">Back to sign in</Link></p></form>; }