"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { CheckCircle2, ChevronDown, ChevronRight, ExternalLink, LoaderCircle, LockKeyhole, Search } from "lucide-react";
import { setFrameworkEnabled } from "@/app/actions/frameworks";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type Control = { id: string; controlId: string; title: string; description: string; category: string; mappings: { risk: { id: string; reference: string; title: string } }[] };
type FrameworkItem = { id: string; name: string; version: string; description: string; industryTags: string; enabled: boolean; controls: Control[] };

export function FrameworkLibrary({ frameworks, canManage, plan, frameworkLimit, enabledCount, mappingCount, mappingLimit, unmappedRisks }: { frameworks: FrameworkItem[]; canManage: boolean; plan: string; frameworkLimit: number; enabledCount: number; mappingCount: number; mappingLimit: number | null; unmappedRisks: { id: string; reference: string; title: string }[] }) {
  const [expanded, setExpanded] = useState<string | null>(frameworks.find((framework) => framework.enabled)?.id ?? null); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [pending, start] = useTransition();
  function toggle(framework: FrameworkItem) { start(async () => { setMessage(""); const result = await setFrameworkEnabled(framework.id, !framework.enabled); if ("error" in result) setMessage(result.error ?? "Unable to update this framework."); }); }
  return <div className="space-y-5">
    <section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-3"><Metric label="Enabled frameworks" value={`${enabledCount} / ${frameworkLimit}`}/><Metric label="Control mappings" value={mappingLimit === null ? `${mappingCount} · Unlimited` : `${mappingCount} / ${mappingLimit}`}/><Metric label="Risks awaiting mapping" value={String(unmappedRisks.length)}/></section>
    {message && <div className="flex flex-col gap-3 rounded-md border border-amber-500/30 bg-amber-500/10 p-4 text-sm sm:flex-row sm:items-center"><LockKeyhole className="size-4 shrink-0 text-amber-600"/><p className="flex-1">{message}</p><Button asChild size="sm"><Link href="/#pricing">View plans</Link></Button></div>}
    <div className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-bold">Framework library</h2><p className="mt-1 text-xs text-muted-foreground">{plan} workspace · enable only the standards used by your programme.</p></div><label className="ml-auto flex w-full items-center gap-2 sm:w-72"><Search className="size-4 text-muted-foreground"/><span className="sr-only">Search controls</span><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search all controls" className="h-9"/></label></div>
    <div className="space-y-3">{frameworks.map((framework) => { const open = expanded === framework.id; const controls = framework.controls.filter((control) => !query || `${control.controlId} ${control.title} ${control.description} ${control.category}`.toLowerCase().includes(query.toLowerCase())); const covered = framework.controls.filter((control) => control.mappings.length).length; return <section key={framework.id} className={cn("overflow-hidden rounded-lg border bg-card", framework.enabled && "border-primary/30")}>
      <div className="flex flex-col gap-4 p-5 md:flex-row md:items-center"><button type="button" onClick={() => setExpanded(open ? null : framework.id)} className="flex min-w-0 flex-1 items-start gap-3 text-left"><span className="mt-0.5 text-muted-foreground">{open ? <ChevronDown className="size-4"/> : <ChevronRight className="size-4"/>}</span><span><span className="flex flex-wrap items-center gap-2"><strong className="text-sm">{framework.name}</strong><span className="text-[10px] text-muted-foreground">{framework.version}</span>{framework.enabled && <span className="rounded bg-primary/10 px-2 py-0.5 text-[9px] font-bold uppercase text-primary">Enabled</span>}</span><span className="mt-1 block max-w-3xl text-xs leading-5 text-muted-foreground">{framework.description}</span></span></button><div className="flex items-center gap-5 pl-7 md:pl-0"><div className="text-right"><p className="text-xs font-bold">{covered} / {framework.controls.length}</p><p className="text-[10px] text-muted-foreground">controls linked</p></div>{canManage && <Button type="button" size="sm" variant={framework.enabled ? "outline" : "default"} disabled={pending} onClick={() => toggle(framework)}>{pending ? <LoaderCircle className="size-3.5 animate-spin"/> : framework.enabled ? "Disable" : "Enable"}</Button>}</div></div>
      {open && <div className="border-t bg-muted/20 p-3 sm:p-5"><div className="overflow-x-auto rounded-md border bg-background"><table className="w-full min-w-[760px] text-left"><thead className="border-b bg-muted/50 text-[10px] uppercase text-muted-foreground"><tr><th className="w-28 p-3">Control</th><th className="p-3">Requirement</th><th className="w-36 p-3">Category</th><th className="w-48 p-3">Mapped risks</th></tr></thead><tbody className="divide-y">{controls.map((control) => <tr key={control.id} className="align-top"><td className="p-3 text-xs font-bold text-primary">{control.controlId}</td><td className="p-3"><p className="text-xs font-bold">{control.title}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{control.description}</p></td><td className="p-3 text-[11px] text-muted-foreground">{control.category}</td><td className="p-3">{control.mappings.length ? control.mappings.slice(0, 3).map(({ risk }) => <Link key={risk.id} href={`/app/risks/${risk.id}`} className="mb-1 flex items-center gap-1 text-[11px] font-semibold text-primary hover:underline">{risk.reference}<ExternalLink className="size-2.5"/></Link>) : <Link href="/app/risks?mapping=unmapped" className="text-[11px] text-muted-foreground hover:text-primary">No mapped risks</Link>}</td></tr>)}{!controls.length && <tr><td colSpan={4} className="p-8 text-center text-xs text-muted-foreground">No controls match this search.</td></tr>}</tbody></table></div></div>}
    </section>; })}</div>
    {unmappedRisks.length > 0 && <section className="border-t pt-5"><h2 className="text-sm font-bold">Risks without framework coverage</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{unmappedRisks.slice(0, 8).map((risk) => <Link key={risk.id} href={`/app/risks/${risk.id}/edit`} className="flex items-center justify-between rounded-md border bg-card p-3 text-xs hover:border-primary/40"><span><strong>{risk.reference}</strong><span className="ml-2 text-muted-foreground">{risk.title}</span></span><ChevronRight className="size-4 text-muted-foreground"/></Link>)}</div></section>}
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-card p-4"><p className="text-[10px] font-bold uppercase text-muted-foreground">{label}</p><p className="mt-2 font-display text-2xl text-primary">{value}</p></div>; }