"use client";

import { useState } from "react";
import { Check, LoaderCircle } from "lucide-react";
import { createAppetiteStatement, createAssessment, createEvidence, createTaxonomyItem, createTreatment, decideTreatment, escalateOverdueActions, submitAssessment, upsertControlProfile } from "@/app/actions/governance";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

type Risk = { id: string; reference: string; title: string; status: string };
type User = { id: string; name: string };
type Control = { id: string; title: string; controlId: string };
type Taxonomy = { id: string; type: string; name: string };
type WorkbenchCapabilities = {
  riskUpdate: boolean;
  assessmentApprove: boolean;
  treatmentManage: boolean;
  treatmentApprove: boolean;
  controlManage: boolean;
  evidenceManage: boolean;
  appetiteManage: boolean;
  taxonomyManage: boolean;
};
function Form({ children, onSubmit, allowed = true, disabledReason }: { children: React.ReactNode; onSubmit: (data: FormData) => Promise<unknown>; allowed?: boolean; disabledReason?: string }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const result = await onSubmit(new FormData(event.currentTarget)); setMessage("error" in (result as object) ? String((result as { error?: string }).error) : "Saved"); setBusy(false); }
  return <form onSubmit={submit} className="grid gap-3"><fieldset disabled={!allowed || busy} className="grid gap-3">{children}<Button disabled={busy || !allowed} title={!allowed ? disabledReason : undefined}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Check className="size-4" />}{allowed ? "Save" : "Save unavailable"}</Button></fieldset>{!allowed && <p className="text-xs text-muted-foreground" role="note">{disabledReason}</p>}{message && <p role="status" className="text-xs text-muted-foreground">{message}</p>}</form>;
}
function Field({ name, label, type = "text", required = true }: { name: string; label: string; type?: string; required?: boolean }) { return <div className="grid gap-1.5"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} /></div>; }
function SelectField({ name, label, options, required = true }: { name: string; label: string; options: Array<{ value: string; label: string }>; required?: boolean }) { return <div className="grid gap-1.5"><Label htmlFor={name}>{label}</Label><select id={name} name={name} required={required} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">Select {label.toLowerCase()}</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>; }

export function GovernanceWorkbench({ risks, plans, assessments, controls, users, taxonomy = [], capabilities }: { risks: Risk[]; plans: Array<{ id: string; summary: string; status: string; riskId: string; strategy: string }>; assessments: Array<{ id: string; revision: number; status: string; riskId: string; type: string }>; controls: Control[]; users: User[]; taxonomy?: Taxonomy[]; capabilities: WorkbenchCapabilities }) {
  const [section, setSection] = useState("assessments"); const riskOptions = risks.map((risk) => ({ value: risk.id, label: `${risk.reference} · ${risk.title}` })); const userOptions = users.map((user) => ({ value: user.id, label: user.name })); const controlOptions = controls.map((control) => ({ value: control.id, label: `${control.controlId} · ${control.title}` })); const tabs = [["assessments", "Assessments"], ["treatments", "Treatment & acceptance"], ["controls", "Controls"], ["evidence", "Evidence"], ["appetite", "Risk appetite"], ["taxonomy", "Taxonomy"]];
  return <div className="grid gap-5 xl:grid-cols-[220px_1fr]"><aside className="flex gap-2 overflow-x-auto xl:flex-col">{tabs.map(([value, label]) => <button key={value} onClick={() => setSection(value)} className={`whitespace-nowrap rounded-md border px-3 py-2 text-left text-xs font-semibold ${section === value ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}>{label}</button>)}</aside><div className="grid gap-5">
    {section === "assessments" && <><Card><CardHeader><h2 className="text-sm font-bold">Create versioned assessment</h2></CardHeader><CardContent><Form allowed={capabilities.riskUpdate} disabledReason="Assessment creation requires risk update permission." onSubmit={(d) => createAssessment({ riskId: d.get("riskId"), type: d.get("type"), likelihood: d.get("likelihood"), impact: d.get("impact"), rationale: d.get("rationale") })}><SelectField name="riskId" label="Risk" options={riskOptions} /><SelectField name="type" label="Assessment type" options={[{ value: "INHERENT", label: "Inherent" }, { value: "RESIDUAL", label: "Residual" }]} /><Field name="likelihood" label="Likelihood (1-5)" type="number" /><Field name="impact" label="Impact (1-5)" type="number" /><Field name="rationale" label="Rationale" /></Form></CardContent></Card><Card><CardHeader><h2 className="text-sm font-bold">Assessment history</h2></CardHeader><CardContent className="grid gap-3">{assessments.map((item) => <div className="flex flex-wrap items-center gap-2 border-b pb-3 text-xs" key={item.id}><span className="font-semibold">{item.type} v{item.revision}</span><span className="text-muted-foreground">{item.status}</span>{item.status === "DRAFT" && <Button size="sm" disabled={!capabilities.riskUpdate} title={capabilities.riskUpdate ? undefined : "Submitting requires risk update permission."} onClick={() => submitAssessment(item.id)}>Submit</Button>}</div>)}</CardContent></Card></>}
    {section === "treatments" && <><Card><CardHeader><h2 className="text-sm font-bold">Create treatment plan</h2></CardHeader><CardContent><Form allowed={capabilities.treatmentManage} disabledReason="Treatment changes require treatment management permission." onSubmit={(d) => createTreatment({ riskId: d.get("riskId"), strategy: d.get("strategy"), summary: d.get("summary"), targetDate: d.get("targetDate") })}><SelectField name="riskId" label="Risk" options={riskOptions} /><Field name="strategy" label="Strategy (MITIGATE, TRANSFER, ACCEPT, AVOID)" /><Field name="summary" label="Treatment summary" /><Field name="targetDate" label="Target date" type="date" /></Form></CardContent></Card><Card><CardHeader><h2 className="text-sm font-bold">Pending treatment decisions</h2></CardHeader><CardContent className="grid gap-3">{plans.filter((plan) => plan.status === "PENDING").map((plan) => <div className="flex flex-wrap items-center gap-2 border-b pb-3 text-xs" key={plan.id}><span className="font-semibold">{plan.strategy}</span><span className="text-muted-foreground">{plan.summary}</span><Button size="sm" disabled={!capabilities.treatmentApprove} onClick={() => decideTreatment(plan.id, "APPROVED", "Approved after governance review")}>Approve</Button><Button size="sm" variant="outline" disabled={!capabilities.treatmentApprove} onClick={() => decideTreatment(plan.id, "REJECTED", "Revise the plan and provide measurable outcomes")}>Reject</Button></div>)}{!capabilities.treatmentApprove && <p className="text-xs text-muted-foreground" role="note">Deciding treatment plans requires treatment approval permission.</p>}<Button variant="outline" disabled={!capabilities.treatmentManage} title={capabilities.treatmentManage ? undefined : "Escalation requires treatment management permission."} onClick={() => escalateOverdueActions()}>Escalate overdue actions</Button></CardContent></Card></>}
    {section === "controls" && <Card><CardHeader><h2 className="text-sm font-bold">Control ownership and effectiveness</h2></CardHeader><CardContent><Form allowed={capabilities.controlManage} disabledReason="Control changes require control management permission." onSubmit={(d) => upsertControlProfile({ frameworkControlId: d.get("frameworkControlId"), ownerId: d.get("ownerId") || undefined, implementationStatus: d.get("implementationStatus"), effectiveness: d.get("effectiveness"), frequency: d.get("frequency"), notes: d.get("notes") })}><SelectField name="frameworkControlId" label="Framework control" options={controlOptions} /><SelectField name="ownerId" label="Control owner" options={userOptions} required={false} /><Field name="implementationStatus" label="Implementation status" /><Field name="effectiveness" label="Effectiveness" /><Field name="frequency" label="Test frequency" required={false} /><Field name="notes" label="Notes" required={false} /></Form><p className="mt-5 text-xs text-muted-foreground">Enabled controls available: {controls.length}. Owners: {users.length}.</p></CardContent></Card>}
    {section === "evidence" && <Card><CardHeader><h2 className="text-sm font-bold">Evidence register</h2></CardHeader><CardContent><Form allowed={capabilities.evidenceManage} disabledReason="Evidence registration requires evidence management permission." onSubmit={(d) => createEvidence({ title: d.get("title"), description: d.get("description"), fileName: d.get("fileName"), mimeType: d.get("mimeType"), sizeBytes: d.get("sizeBytes") || undefined, checksum: d.get("checksum") || undefined, expiresAt: d.get("expiresAt") || undefined })}><Field name="title" label="Evidence title" /><Field name="description" label="Description" required={false} /><Field name="fileName" label="File name" required={false} /><Field name="mimeType" label="MIME type" required={false} /><Field name="sizeBytes" label="Size in bytes" type="number" required={false} /><Field name="checksum" label="Checksum" required={false} /><Field name="expiresAt" label="Expiry date" type="date" required={false} /></Form><p className="mt-4 text-xs text-muted-foreground">This release stores tenant-scoped evidence metadata. Private object storage, malware scanning, and signed delivery remain deployment requirements.</p></CardContent></Card>}
    {section === "appetite" && <Card><CardHeader><h2 className="text-sm font-bold">Risk appetite and breach evaluation</h2></CardHeader><CardContent><Form allowed={capabilities.appetiteManage} disabledReason="Appetite changes require appetite management permission." onSubmit={(d) => createAppetiteStatement({ name: d.get("name"), category: d.get("category") || undefined, maximumScore: d.get("maximumScore"), rationale: d.get("rationale"), effectiveFrom: d.get("effectiveFrom") })}><Field name="name" label="Statement name" /><Field name="category" label="Category (optional)" required={false} /><Field name="maximumScore" label="Maximum score (1-25)" type="number" /><Field name="rationale" label="Rationale" /><Field name="effectiveFrom" label="Effective from" type="date" /></Form><p className="mt-4 text-xs text-muted-foreground">Breach creation is tenant-scoped and idempotent per risk, appetite statement, and open status.</p></CardContent></Card>}
    {section === "taxonomy" && <Card><CardHeader><h2 className="text-sm font-bold">Configurable taxonomy</h2></CardHeader><CardContent><Form allowed={capabilities.taxonomyManage} disabledReason="Taxonomy changes require taxonomy management permission." onSubmit={(d) => createTaxonomyItem({ type: d.get("type"), name: d.get("name"), description: d.get("description") || undefined })}><SelectField name="type" label="Taxonomy type" options={["RISK_CATEGORY", "BUSINESS_UNIT", "OBJECTIVE", "RISK_SOURCE", "REGULATORY_DOMAIN", "TAG"].map((value) => ({ value, label: value.replaceAll("_", " ") }))} /><Field name="name" label="Name" /><Field name="description" label="Description" required={false} /></Form><p className="mt-4 text-xs text-muted-foreground">Configured values are available to risk forms after refresh and are always validated against this workspace. Active items: {taxonomy.length}.</p></CardContent></Card>}
  </div></div>;
}