"use client";
import Link from "next/link";
import { useState } from "react";
import { signIn } from "next-auth/react";
import { useRouter } from "next/navigation";
import { LoaderCircle, LockKeyhole, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
 export function LoginForm() { const router = useRouter(); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); const result = await signIn("credentials", { email: data.get("email"), password: data.get("password"), redirect: false }); if (result?.error) { setError("Email or password is incorrect."); setLoading(false); } else { router.push("/app"); router.refresh(); } } return <form onSubmit={submit} className="space-y-5"><div className="space-y-2"><Label htmlFor="email" className="text-xs font-semibold text-slate-300">Email address</Label><div className="relative"><Mail className="absolute left-3 top-3 size-4 text-slate-500" aria-hidden="true"/><Input id="email" name="email" type="email" autoComplete="email" required className="border-white/10 bg-white/5 pl-10 text-white"/></div></div><div className="space-y-2"><Label htmlFor="password" className="text-xs font-semibold text-slate-300">Password</Label><div className="relative"><LockKeyhole className="absolute left-3 top-3 size-4 text-slate-500" aria-hidden="true"/><Input id="password" name="password" type="password" autoComplete="current-password" required className="border-white/10 bg-white/5 pl-10 text-white"/></div></div>{error && <p role="alert" aria-live="polite" className="text-sm text-red-300">{error}</p>}<Button className="h-11 w-full" disabled={loading}>{loading && <LoaderCircle className="size-4" aria-hidden="true"/>}Sign in to workspace</Button><div className="grid grid-cols-1 gap-3 text-center text-xs sm:grid-cols-2"><Link href="/magic-link" className="text-primary hover:underline">Email me a link</Link><Link href="/register" className="text-primary hover:underline">Create workspace</Link></div><p className="text-center text-xs leading-5 text-slate-500">Use the credentials configured for this local environment.</p></form>; }