"use client";
import { useState } from "react";
import { updateNotificationPreferences, updateReviewReminderSettings } from "@/app/actions/notifications";
import { Button } from "@/components/ui/button";

export function NotificationSettings({ user, tenant, owner }: { user: { reviewEmailsEnabled: boolean; assignmentEmailsEnabled: boolean; exportEmailsEnabled: boolean }; tenant: { reviewRemindersEnabled: boolean; reviewReminderCadence: string; plan: string }; owner: boolean }) {
  const [message, setMessage] = useState("");
  async function saveUser(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await updateNotificationPreferences({ reviewEmailsEnabled: data.get("reviews") === "on", assignmentEmailsEnabled: data.get("assignments") === "on", exportEmailsEnabled: data.get("exports") === "on" }); setMessage("error" in result ? result.error ?? "Unable to save." : "Email preferences updated."); }
  async function saveTenant(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await updateReviewReminderSettings({ enabled: data.get("enabled") === "on", cadence: String(data.get("cadence")) }); setMessage("error" in result ? result.error ?? "Unable to save." : "Workspace reminders updated."); }
  return <div className="grid gap-5 lg:grid-cols-2"><form onSubmit={saveUser} className="rounded-lg border p-5"><h2 className="text-sm font-bold">Your email preferences</h2><div className="mt-4 grid gap-3 text-sm">{[["reviews","Risk review reminders",user.reviewEmailsEnabled],["assignments","Assignments and overdue actions",user.assignmentEmailsEnabled],["exports","Report and export delivery",user.exportEmailsEnabled]].map(([id,label,checked])=><label key={String(id)} className="flex items-center gap-3"><input name={String(id)} type="checkbox" defaultChecked={Boolean(checked)} className="size-4 accent-primary"/><span>{String(label)}</span></label>)}</div><Button className="mt-5" size="sm">Save preferences</Button></form>{owner&&<form onSubmit={saveTenant} className="rounded-lg border p-5"><h2 className="text-sm font-bold">Workspace review reminders</h2><p className="mt-1 text-xs text-muted-foreground">Plan: {tenant.plan}. Use days before review; 0 means the day it becomes overdue.</p><label className="mt-4 flex items-center gap-3 text-sm"><input name="enabled" type="checkbox" defaultChecked={tenant.reviewRemindersEnabled} className="size-4 accent-primary"/> Enable review reminders</label><label className="mt-4 block text-xs font-semibold">Cadence<input name="cadence" defaultValue={tenant.reviewReminderCadence} className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm"/></label><Button className="mt-5" size="sm">Save workspace settings</Button></form>}{message&&<p role="status" className="text-xs text-primary lg:col-span-2">{message}</p>}</div>;
}