"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowUpDown, Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { RiskBadge } from "@/components/risk-badge";
import { Badge } from "@/components/ui/badge";
import { formatDate, formatEnum } from "@/lib/utils";
type Row = { id: string; reference: string; title: string; category: string; status: string; residualScore: number | null; inherentScore: number; nextReviewDate: string; updatedAt: string; owner: { name: string } };
export function RiskTable({ risks }: { risks: Row[] }) { const [query, setQuery] = useState(""); const [level, setLevel] = useState("all"); const [ascending, setAscending] = useState(false); const rows = useMemo(() => risks.filter(r => `${r.reference} ${r.title} ${r.owner.name}`.toLowerCase().includes(query.toLowerCase())).filter(r => { const s = r.residualScore ?? r.inherentScore; return level === "all" || level === "high" && s >= 15 || level === "medium" && s >= 7 && s < 15 || level === "low" && s < 7; }).sort((a,b) => ascending ? (a.residualScore ?? a.inherentScore) - (b.residualScore ?? b.inherentScore) : (b.residualScore ?? b.inherentScore) - (a.residualScore ?? a.inherentScore)), [risks, query, level, ascending]); return <div className="overflow-hidden rounded-lg border bg-card"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by risk, reference, or owner" className="pl-9"/></div><select aria-label="Filter by exposure" value={level} onChange={e => setLevel(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="all">All exposure</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><button onClick={() => setAscending(x => !x)} className="flex h-10 items-center gap-2 rounded-md border px-3 text-sm"><ArrowUpDown className="size-4"/>Score</button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-muted/40 text-[10px] uppercase tracking-[.1em] text-muted-foreground"><tr><th className="px-5 py-3">Risk</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Owner</th><th className="px-5 py-3">Exposure</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Next review</th></tr></thead><tbody>{rows.map(r => <tr key={r.id} className="border-t transition-colors hover:bg-accent/30"><td className="px-5 py-4"><Link href={`/app/risks/${r.id}`} className="block"><span className="text-[10px] font-bold text-primary">{r.reference}</span><p className="mt-1 max-w-sm truncate text-sm font-semibold">{r.title}</p></Link></td><td className="px-5 py-4 text-xs text-muted-foreground">{formatEnum(r.category)}</td><td className="px-5 py-4 text-xs">{r.owner.name}</td><td className="px-5 py-4"><RiskBadge score={r.residualScore}/></td><td className="px-5 py-4"><Badge className="border-border bg-muted text-muted-foreground">{formatEnum(r.status)}</Badge></td><td className="px-5 py-4 text-xs text-muted-foreground">{formatDate(new Date(r.nextReviewDate))}</td></tr>)}</tbody></table></div>{rows.length === 0 && <p className="p-10 text-center text-sm text-muted-foreground">No risks match these filters.</p>}</div>; }