import { RiskCategory } from "@prisma/client";
import { db } from "@/lib/db";

export const complianceCatalog = [
  { framework: "ISO/IEC 27001:2022", jurisdiction: "Global", reference: "A.5.19", title: "Information security in supplier relationships", excerpt: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier products or services.", metric: "Supplier security reviews completed before onboarding and at the defined review cadence.", sourceUrl: "https://www.iso.org/standard/27001", categories: "THIRD_PARTY,CYBERSECURITY", keywords: "supplier vendor third-party cloud", industry: "ALL" },
  { framework: "NIST CSF 2.0", jurisdiction: "Global / United States", reference: "GV.SC-06", title: "Supplier risk planning", excerpt: "Planning and due diligence are performed to reduce risks before entering into formal supplier or other third-party relationships.", metric: "Percentage of critical suppliers with completed due diligence and current risk tier.", sourceUrl: "https://www.nist.gov/cyberframework", categories: "THIRD_PARTY,CYBERSECURITY", keywords: "supplier vendor due diligence", industry: "ALL" },
  { framework: "GDPR", jurisdiction: "European Union / EEA", reference: "Article 32", title: "Security of processing", excerpt: "The controller and processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk.", metric: "Security measures tested regularly; material personal-data risks have documented treatment.", sourceUrl: "https://eur-lex.europa.eu/eli/reg/2016/679/oj", categories: "PRIVACY,CYBERSECURITY,THIRD_PARTY", keywords: "personal data privacy breach processor encryption", industry: "ALL" },
  { framework: "HIPAA Security Rule", jurisdiction: "United States", reference: "45 CFR 164.308(a)(1)", title: "Security management process", excerpt: "Implement policies and procedures to prevent, detect, contain, and correct security violations, including an accurate and thorough assessment of potential risks and vulnerabilities.", metric: "Enterprise security risk analysis is current and remediation actions have accountable owners.", sourceUrl: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-C", categories: "PRIVACY,CYBERSECURITY,OPERATIONAL", keywords: "patient phi health clinical medical security", industry: "HEALTHCARE" },
  { framework: "PCI DSS v4.0.1", jurisdiction: "Global payments", reference: "Requirement 12.3.1", title: "Targeted risk analysis", excerpt: "Each PCI DSS requirement that provides flexibility for how frequently it is performed is supported by a targeted risk analysis that is documented and reviewed.", metric: "Targeted risk analyses identify assets, threats, likelihood, impact, and justified frequency.", sourceUrl: "https://www.pcisecuritystandards.org/document_library", categories: "CYBERSECURITY,COMPLIANCE,OPERATIONAL", keywords: "card payment merchant transaction wallet", industry: "FINTECH" },
  { framework: "SOC 2 Trust Services Criteria", jurisdiction: "Global assurance", reference: "CC3.2", title: "Risk identification and analysis", excerpt: "The entity identifies risks to the achievement of its objectives and analyzes risks as a basis for determining how the risks should be managed.", metric: "Risk register maps material risks to objectives, controls, owners, and treatment decisions.", sourceUrl: "https://www.aicpa-cima.com/resources/landing/system-and-organization-controls-soc-suite-of-services", categories: "OPERATIONAL,STRATEGIC,CYBERSECURITY,COMPLIANCE", keywords: "service control assurance availability confidentiality", industry: "ALL" },
  { framework: "DORA", jurisdiction: "European Union financial sector", reference: "Article 6", title: "ICT risk management framework", excerpt: "Financial entities shall have a sound, comprehensive and well-documented ICT risk management framework as part of their overall risk management system.", metric: "Critical ICT assets, dependencies, scenarios, controls, and residual risk are reviewed at least annually.", sourceUrl: "https://eur-lex.europa.eu/eli/reg/2022/2554/oj", categories: "CYBERSECURITY,RESILIENCE,THIRD_PARTY", keywords: "bank fintech ict outage resilience cloud", industry: "FINTECH" },
  { framework: "Basel Committee Operational Resilience", jurisdiction: "Global banking", reference: "Principle 2", title: "Operational resilience governance", excerpt: "Banks should leverage their respective functions for the management of operational risk to establish a robust operational resilience approach.", metric: "Board-approved tolerances exist for disruption to critical operations and are scenario tested.", sourceUrl: "https://www.bis.org/bcbs/publ/d516.htm", categories: "OPERATIONAL,RESILIENCE,FINANCIAL", keywords: "bank financial service disruption tolerance", industry: "FINTECH" },
] as const;

export async function ensureComplianceCatalog(tenantId: string) {
  await Promise.all(complianceCatalog.map((item) => db.complianceReference.upsert({ where: { tenantId_framework_reference: { tenantId, framework: item.framework, reference: item.reference } }, update: { ...item }, create: { tenantId, ...item } })));
}

export async function linkComplianceToRisk(risk: { id: string; tenantId: string; category: RiskCategory; title: string; description: string }) {
  await ensureComplianceCatalog(risk.tenantId);
  const references = await db.complianceReference.findMany({ where: { tenantId: risk.tenantId } });
  const text = `${risk.title} ${risk.description}`.toLowerCase();
  const matches = references.filter((reference) => reference.categories.split(",").includes(risk.category) || reference.keywords.split(" ").some((keyword) => text.includes(keyword))).slice(0, 6);
  await db.$transaction([
    db.riskComplianceLink.deleteMany({ where: { riskId: risk.id } }),
    ...matches.map((reference) => db.riskComplianceLink.create({ data: { riskId: risk.id, referenceId: reference.id, rationale: reference.categories.includes(risk.category) ? `Triggered by ${risk.category.toLowerCase().replaceAll("_", " ")} classification.` : "Triggered by terms in the risk statement." } })),
  ]);
  return matches;
}