import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { appUrl, createToken, hashToken } from "@/lib/tokens";

export type NotificationType =
  | "INVITATION"
  | "MAGIC_LINK"
  | "REVIEW_REMINDER"
  | "EXPORT_DELIVERY"
  | "ACTION_ASSIGNED"
  | "ACTION_OVERDUE"
  | "HIGH_RESIDUAL_RISK"
  | "EMERGING_RISK_SETTLED"
  | "TREATMENT_CHANGED";

type EmailInput = {
  tenantId: string;
  userId?: string;
  recipient: string;
  type: NotificationType;
  subject: string;
  eyebrow: string;
  heading: string;
  paragraphs: string[];
  cta?: { label: string; url: string };
  details?: Array<{ label: string; value: string }>;
  relatedEntityType?: string;
  relatedEntityId?: string;
  dedupeKey?: string;
};

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character]!);

function renderEmail(input: EmailInput) {
  const detailsHtml = input.details?.length ? `<table role="presentation" style="width:100%;margin:24px 0;border-collapse:collapse">${input.details.map((item) => `<tr><td style="padding:10px 0;border-bottom:1px solid #dbe7e9;color:#60727a;font-size:13px">${escapeHtml(item.label)}</td><td style="padding:10px 0;border-bottom:1px solid #dbe7e9;color:#0a2540;font-size:13px;font-weight:700;text-align:right">${escapeHtml(item.value)}</td></tr>`).join("")}</table>` : "";
  const ctaHtml = input.cta ? `<p style="margin:28px 0"><a href="${escapeHtml(input.cta.url)}" style="display:inline-block;background:#00a896;color:#ffffff;text-decoration:none;font-weight:700;font-size:14px;padding:12px 18px;border-radius:6px">${escapeHtml(input.cta.label)}</a></p><p style="font-size:12px;color:#71848b;word-break:break-all">${escapeHtml(input.cta.url)}</p>` : "";
  const html = `<!doctype html><html><body style="margin:0;background:#eef4f5;font-family:Arial,sans-serif;color:#173746"><table role="presentation" style="width:100%;border-collapse:collapse"><tr><td style="padding:32px 16px"><table role="presentation" style="max-width:620px;width:100%;margin:auto;background:#ffffff;border-collapse:collapse;border:1px solid #dbe7e9"><tr><td style="background:#0a2540;padding:26px 32px;color:#ffffff"><div style="font-size:12px;font-weight:700;letter-spacing:1px;color:#a9ede5">BEYONDBEAMS GRC</div><div style="font-size:24px;font-weight:700;margin-top:8px">${escapeHtml(input.heading)}</div></td></tr><tr><td style="padding:30px 32px"><div style="font-size:11px;font-weight:700;color:#008c7d;text-transform:uppercase">${escapeHtml(input.eyebrow)}</div>${input.paragraphs.map((paragraph) => `<p style="font-size:15px;line-height:1.65;margin:16px 0;color:#36515d">${escapeHtml(paragraph)}</p>`).join("")}${detailsHtml}${ctaHtml}<p style="margin-top:30px;font-size:12px;color:#71848b">This message was generated by BeyondBeams GRC for your organisation.</p></td></tr></table></td></tr></table></body></html>`;
  const text = [`BEYONDBEAMS GRC`, input.heading, input.eyebrow, "", ...input.paragraphs, "", ...(input.details?.map((item) => `${item.label}: ${item.value}`) ?? []), ...(input.cta ? ["", `${input.cta.label}: ${input.cta.url}`] : [])].join("\n");
  return { html, text };
}

async function sendWithResend(recipient: string, subject: string, html: string, text: string) {
  const key = process.env.RESEND_API_KEY;
  if (!key) throw new Error("RESEND_API_KEY is required when EMAIL_PROVIDER=resend");
  const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: process.env.EMAIL_FROM ?? "BeyondBeams GRC <notifications@example.com>", to: [recipient], subject, html, text }) });
  if (!response.ok) throw new Error(`Email provider returned ${response.status}`);
}

export async function sendNotificationEmail(input: EmailInput) {
  const rendered = renderEmail(input);
  const provider = process.env.EMAIL_PROVIDER ?? "preview";
  if (process.env.NODE_ENV === "production" && provider === "preview") throw new Error("EMAIL_PROVIDER=preview is not allowed in production");
  const local = process.env.NODE_ENV !== "production" && provider === "preview";
  const previewToken = local ? createToken() : undefined;
  try {
    if (!local) await sendWithResend(input.recipient, input.subject, rendered.html, rendered.text);
    const notification = await db.notification.create({ data: { tenantId: input.tenantId, userId: input.userId, recipient: input.recipient.toLowerCase(), type: input.type, subject: input.subject, htmlBody: rendered.html, textBody: rendered.text, status: "SENT", provider: local ? "local-preview" : "resend", relatedEntityType: input.relatedEntityType, relatedEntityId: input.relatedEntityId, dedupeKey: input.dedupeKey, previewTokenHash: previewToken ? hashToken(previewToken) : undefined } });
    const auditActor = input.userId ?? (await db.membership.findFirst({ where: { tenantId: input.tenantId, acceptedAt: { not: null }, role: "OWNER", userId: { not: null } }, select: { userId: true } }))?.userId;
    if (auditActor) await db.auditEvent.create({ data: { tenantId: input.tenantId, actorId: auditActor, action: "CREATE", entityType: "Notification", entityId: notification.id, summary: `Sent ${input.type} notification to ${input.recipient}` } });
    const previewUrl = previewToken ? `${appUrl()}/email-preview/${previewToken}` : undefined;
    if (local) console.info(`[BeyondBeams email preview] prepared for ${input.recipient}; preview URL is available in the local response.`);
    return { sent: true as const, notificationId: notification.id, previewUrl };
  } catch (error) {
    if (input.dedupeKey && error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return { sent: false as const, duplicate: true as const };
    const failed = await db.notification.create({ data: { tenantId: input.tenantId, userId: input.userId, recipient: input.recipient.toLowerCase(), type: input.type, subject: input.subject, htmlBody: rendered.html, textBody: rendered.text, status: "FAILED", provider: local ? "local-preview" : "resend", relatedEntityType: input.relatedEntityType, relatedEntityId: input.relatedEntityId } }).catch(() => undefined);
    if (failed) { const auditActor = input.userId ?? (await db.membership.findFirst({ where: { tenantId: input.tenantId, acceptedAt: { not: null }, role: "OWNER", userId: { not: null } }, select: { userId: true } }))?.userId; if (auditActor) await db.auditEvent.create({ data: { tenantId: input.tenantId, actorId: auditActor, action: "CREATE", entityType: "Notification", entityId: failed.id, summary: `Failed ${input.type} notification to ${input.recipient}` } }).catch(() => undefined); }
    console.error("Email delivery failed", error);
    return { sent: false as const, error: "Email delivery failed." };
  }
}