export const industryTemplates = [
  { industry:"Healthcare",area:"Clinical operations",title:"Patient safety event",risk:"A process or technology failure may cause delayed, incorrect, or missed care.",controls:["Clinical escalation protocol","Safety event review","Downtime procedure"],frameworks:["HIPAA","ISO 7101","Local health regulation"] },
  { industry:"Healthcare",area:"Health information",title:"Protected health information exposure",risk:"Unauthorised access or disclosure may compromise patient privacy and trigger notification duties.",controls:["Minimum necessary access","Audit logging","Breach response"],frameworks:["HIPAA","GDPR","ISO 27001"] },
  { industry:"Healthcare",area:"Medical devices",title:"Connected device compromise",risk:"A vulnerable connected medical device may affect patient safety, service availability, or clinical data.",controls:["Device inventory","Security monitoring","Patch risk assessment"],frameworks:["FDA guidance","NIST CSF","ISO 14971"] },
  { industry:"Fintech",area:"Banking",title:"Core banking disruption",risk:"A critical platform failure may prevent customers accessing funds or completing regulated transactions.",controls:["Resilience testing","Recovery objectives","Manual continuity procedures"],frameworks:["DORA","Basel operational resilience","Local prudential rules"] },
  { industry:"Fintech",area:"Payments & wallets",title:"Fraud and account takeover",risk:"Compromised credentials or transaction controls may enable unauthorised payments and customer loss.",controls:["Strong customer authentication","Transaction monitoring","Velocity limits"],frameworks:["PCI DSS","PSD2/PSD3","Local payments law"] },
  { industry:"Fintech",area:"Crypto assets",title:"Private-key compromise",risk:"Loss or misuse of cryptographic keys may result in irreversible loss of customer or treasury assets.",controls:["HSM or MPC custody","Withdrawal allow-listing","Key ceremony"],frameworks:["MiCA","FATF guidance","Local VASP rules"] },
  { industry:"Fintech",area:"Lending",title:"Model-driven unfair lending",risk:"Data or model bias may produce unfair, opaque, or non-compliant credit decisions.",controls:["Fairness testing","Adverse-action reasons","Model governance"],frameworks:["ECOA / Regulation B","EU AI Act","Consumer credit law"] },
  { industry:"Fintech",area:"Insurtech",title:"Claims automation error",risk:"Automated decisions may incorrectly delay or deny valid claims and harm customers.",controls:["Human review thresholds","Outcome monitoring","Complaint analysis"],frameworks:["Insurance conduct rules","Privacy law","AI governance"] },
  { industry:"Fintech",area:"Stocks & forex",title:"Market abuse surveillance gap",risk:"Insufficient surveillance may fail to detect manipulation, insider dealing, or abusive trading patterns.",controls:["Trade surveillance","Restricted lists","Alert disposition QA"],frameworks:["MAR","SEC / FINRA rules","Local securities law"] },
] as const;