import { Building2, ClipboardCheck, FileText, Gauge, ListChecks, Scale, Siren, SlidersHorizontal } from "lucide-react";

export const moduleDefinitions = {
  assessments: { title: "Risk assessment & scoring", eyebrow: "Decision analysis", description: "Document assessment context, challenge assumptions, and produce a defensible decision.", icon: Gauge, titleLabel: "Assessment name", detailsLabel: "Scenario, assumptions, and scoring rationale", outcomeLabel: "Decision and recommended response", defaultOutcome: "Validate the score with the risk owner, confirm control assumptions, and set the next review date." },
  treatments: { title: "Risk treatment & action plans", eyebrow: "Response planning", description: "Turn treatment decisions into owned, time-bound actions with a measurable target state.", icon: ListChecks, titleLabel: "Treatment plan", detailsLabel: "Risk response, dependencies, and milestones", outcomeLabel: "Target state and success measure", defaultOutcome: "Assign each action, confirm funding and dependencies, then measure residual exposure after completion." },
  controls: { title: "Control management & effectiveness", eyebrow: "Control assurance", description: "Define controls, test their design and operation, and record evidence-backed conclusions.", icon: SlidersHorizontal, titleLabel: "Control name", detailsLabel: "Control objective, activity, frequency, and evidence", outcomeLabel: "Effectiveness conclusion and remediation", defaultOutcome: "Retest failed evidence, assign remediation, and update the linked residual risk assessment." },
  compliance: { title: "Compliance mapping & evidence", eyebrow: "Worldwide obligations", description: "Search authoritative references, map requirements, and record evidence or remediation decisions.", icon: Scale, titleLabel: "Mapping or evidence request", detailsLabel: "Scope, obligation, control, and evidence description", outcomeLabel: "Gap decision and next action", defaultOutcome: "Confirm applicability with counsel or compliance leadership, attach current evidence, and remediate any gap." },
  vendors: { title: "Third-party / vendor risk", eyebrow: "External dependency", description: "Assess supplier criticality, data access, resilience, concentration, and contractual safeguards.", icon: Building2, titleLabel: "Vendor assessment", detailsLabel: "Service, data, criticality, due diligence, and concentration", outcomeLabel: "Risk tier and onboarding decision", defaultOutcome: "Complete due diligence, agree contractual controls, assign a risk tier, and schedule ongoing monitoring." },
  incidents: { title: "Incident & issue management", eyebrow: "Response and recovery", description: "Capture events, impact, root cause, containment, and corrective action in one accountable record.", icon: Siren, titleLabel: "Incident or issue", detailsLabel: "Timeline, affected services, impact, containment, and root cause", outcomeLabel: "Corrective action and closure criteria", defaultOutcome: "Contain impact, preserve evidence, complete root-cause analysis, and verify corrective actions before closure." },
  audit: { title: "Audit & assurance", eyebrow: "Independent challenge", description: "Plan assurance work, capture findings, and drive evidence-backed management responses.", icon: ClipboardCheck, titleLabel: "Audit or assurance review", detailsLabel: "Objective, scope, criteria, sample, and finding", outcomeLabel: "Opinion, recommendation, and management response", defaultOutcome: "Agree the finding and owner, set a due date, and independently validate remediation evidence." },
  policies: { title: "Policy & procedure management", eyebrow: "Governance documents", description: "Draft, approve, attest, review, and retire policies with clear ownership and applicability.", icon: FileText, titleLabel: "Policy or procedure", detailsLabel: "Purpose, scope, requirements, exceptions, and approvers", outcomeLabel: "Publication and attestation plan", defaultOutcome: "Obtain approval, publish the controlled version, collect attestations, and schedule periodic review." },
} as const;

export type ModuleSlug = keyof typeof moduleDefinitions;
export function isModuleSlug(value: string): value is ModuleSlug { return value in moduleDefinitions; }