import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, ArrowDownRight, ArrowRight, BarChart3, Bell, CheckCircle2, ChevronDown, ClipboardCheck, Download, FileBarChart, FileText, LayoutDashboard, Menu, Plus, Search, Settings, Shield, ShieldCheck, SlidersHorizontal, Target, Users, X } from 'lucide-react'

const API = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000/api/v1'
const nav = [['Overview', LayoutDashboard], ['Risk register', FileText], ['Heat map', Target], ['Treatments', ClipboardCheck], ['Reports', FileBarChart]]
const seedRisks = [
  ['1','RSK-0021','Third-party data exposure','A critical supplier may expose regulated customer data through weak access controls.','Cybersecurity','Technology','Maya Chen','Treatment in progress','Reduce','2026-09-15',5,5,3,4,'Quarterly supplier access assurance','Complete privileged access recertification',65],
  ['2','RSK-0022','Regulatory reporting delay','Incomplete source data may delay mandatory submissions and trigger supervisory action.','Compliance','Legal & Compliance','Jon Bell','Treatment in progress','Reduce','2026-08-28',4,4,2,3,'Submission data quality review','Automate source data validation',78],
  ['3','RSK-0023','Key person dependency','Loss of specialist knowledge may interrupt financial close and assurance activities.','People','Finance','Priya Shah','Monitoring','Reduce','2026-10-10',3,4,2,3,'Critical role succession review','Complete cross-training plan',42],
  ['4','RSK-0024','Cloud service interruption','A regional cloud outage may make customer operations unavailable beyond tolerance.','Resilience','Technology','Maya Chen','Monitoring','Reduce','2026-09-30',3,5,2,3,'Quarterly recovery exercise','Validate regional failover',20],
  ['5','RSK-0025','Revenue forecast volatility','Rapid market changes may reduce forecast accuracy and investment capacity.','Strategic','Executive','Elena Rossi','Accepted','Accept','2026-11-01',3,3,2,2,'Scenario planning review','Refresh downside scenarios',90],
  ['6','RSK-0026','Vendor concentration','Dependence on one logistics provider may disrupt service delivery during peak demand.','Third party','Operations','Owen Wright','Treatment in progress','Transfer','2026-09-05',4,3,3,2,'Supplier capacity monitoring','Contract secondary logistics provider',35],
].map(([id,reference,title,description,category,business_unit,owner,status,treatment_strategy,review_date,il,ii,rl,ri,control,action,progress]) => ({ id,reference,title,description,category,business_unit,owner,status,treatment_strategy,review_date,inherent:{likelihood:il,impact:ii,score:il*ii,level:levelFor(il*ii),rationale:'Exposure assessed against the current operating context.'},residual:{likelihood:rl,impact:ri,score:rl*ri,level:levelFor(rl*ri),rationale:'Residual exposure reflects documented control operation.'},controls:[{id:`CTL-${id}`,title:control,owner,type:'Detective',effectiveness:'Largely effective',status:'Implemented'}],actions:[{id:`ACT-${id}`,title:action,owner,due_date:review_date,status:progress<40?'Blocked':'In progress',progress}]}))

function levelFor(score) { return score >= 20 ? 'Critical' : score >= 12 ? 'High' : score >= 6 ? 'Moderate' : 'Low' }
const assessed = risk => risk.residual || risk.inherent
const initials = name => name.split(' ').map(part => part[0]).join('').slice(0,2)

export default function RiskAssessment() {
  const [risks,setRisks] = useState(seedRisks), [active,setActive] = useState('Overview'), [query,setQuery] = useState(''), [level,setLevel] = useState('All levels'), [selected,setSelected] = useState(null), [creating,setCreating] = useState(false), [mobile,setMobile] = useState(false), [mapMode,setMapMode] = useState('residual'), [api,setApi] = useState('connecting')
  useEffect(() => { fetch(`${API}/risks`).then(r => r.ok ? r.json() : Promise.reject()).then(data => { if(data.length) setRisks(data); setApi('connected') }).catch(() => setApi('demo')) }, [])
  const visible = useMemo(() => risks.filter(r => `${r.reference} ${r.title} ${r.owner} ${r.category}`.toLowerCase().includes(query.toLowerCase()) && (level === 'All levels' || assessed(r).level === level)), [risks,query,level])
  const inherentTotal = risks.reduce((sum,r) => sum+r.inherent.score,0), residualTotal = risks.reduce((sum,r) => sum+assessed(r).score,0)
  const metrics = { total:risks.length, appetite:risks.filter(r => assessed(r).score >= 12).length, coverage:Math.round(risks.filter(r => r.controls?.length || r.actions?.length).length/risks.length*100), reduction:Math.round((inherentTotal-residualTotal)/inherentTotal*100), actions:risks.flatMap(r=>r.actions||[]).filter(a=>a.status!=='Complete').length }
  const createRisk = async event => { event.preventDefault(); const f=new FormData(event.currentTarget), il=+f.get('il'),ii=+f.get('ii'),rl=+f.get('rl'),ri=+f.get('ri'); const payload={title:f.get('title'),description:f.get('description'),category:f.get('category'),business_unit:f.get('unit'),owner:f.get('owner'),status:'Open',treatment_strategy:f.get('strategy'),review_date:f.get('date'),inherent:{likelihood:il,impact:ii,rationale:f.get('inherentRationale')},residual:{likelihood:rl,impact:ri,rationale:f.get('residualRationale')}}; try { const response=await fetch(`${API}/risks`,{method:'POST',headers:{'Content-Type':'application/json','X-Actor-Name':'Maya Chen'},body:JSON.stringify(payload)}); if(!response.ok) throw Error(); const created=await response.json(); setRisks(old=>[created,...old]); setApi('connected') } catch { setRisks(old=>[{...payload,id:crypto.randomUUID(),reference:`RSK-${String(old.length+21).padStart(4,'0')}`,inherent:{...payload.inherent,score:il*ii,level:levelFor(il*ii)},residual:{...payload.residual,score:rl*ri,level:levelFor(rl*ri)},controls:[],actions:[]},...old]); setApi('demo') } setCreating(false) }
  return <div className="shell"><Sidebar active={active} go={setActive} mobile={mobile} close={()=>setMobile(false)}/><div className="main"><Topbar active={active} api={api} menu={()=>setMobile(true)}/><main>
    {active==='Overview' && <Overview risks={risks} metrics={metrics} open={setSelected} go={setActive} mode={mapMode} setMode={setMapMode}/>} 
    {active==='Risk register' && <Register risks={visible} query={query} setQuery={setQuery} level={level} setLevel={setLevel} open={setSelected} create={()=>setCreating(true)}/>} 
    {active==='Heat map' && <HeatPage risks={risks} mode={mapMode} setMode={setMapMode} open={setSelected}/>} 
    {active==='Treatments' && <Treatments risks={risks} open={setSelected}/>} 
    {active==='Reports' && <Reports risks={risks} metrics={metrics}/>} 
  </main></div>{selected&&<Drawer risk={selected} close={()=>setSelected(null)}/>} {creating&&<RiskModal close={()=>setCreating(false)} submit={createRisk}/>}</div>
}

function Sidebar({active,go,mobile,close}) { return <><div className={`scrim ${mobile?'show':''}`} onClick={close}/><aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><i><Shield size={20}/></i><span>Northstar<b>GRC</b></span><button onClick={close}><X size={18}/></button></div><div className="workspace"><i>AC</i><span><small>WORKSPACE</small><b>Acme Corporation</b></span><ChevronDown size={14}/></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>{go(label);close()}}><Icon size={17}/>{label}{label==='Treatments'&&<b>5</b>}</button>)}</nav><div className="governance"><small>GOVERNANCE</small><button><Users size={17}/>People & access</button><button><Activity size={17}/>Audit trail</button><button><Settings size={17}/>Configuration</button></div><div className="profile"><Avatar name="Maya Chen"/><span><b>Maya Chen</b><small>Risk manager</small></span></div></aside></> }
function Topbar({active,api,menu}) { return <header className="topbar"><button className="menu" onClick={menu}><Menu size={19}/></button><p><span>Acme Corporation / </span><b>{active}</b></p><div><i className={`connection ${api}`}>{api==='connected'?'API connected':api==='demo'?'Local demo data':'Connecting'}</i><button><Bell size={17}/></button><Avatar name="Maya Chen"/></div></header> }
function Intro({kicker,title,copy,action}) { return <div className="intro"><div><small>{kicker}</small><h1>{title}</h1><p>{copy}</p></div>{action}</div> }
function SectionHead({title,copy,action}) { return <header className="section-head"><div><h2>{title}</h2><p>{copy}</p></div>{action}</header> }
function Button({children,onClick,secondary=false}) { return <button className={secondary?'secondary':'primary'} onClick={onClick}>{children}</button> }
function Avatar({name}) { return <i className="avatar">{initials(name)}</i> }
function Score({item}) { return <span className={`score ${item.level.toLowerCase()}`}><b>{item.score}</b><small>{item.level}</small></span> }

function Overview({risks,metrics,open,go,mode,setMode}) { const priorities=[...risks].sort((a,b)=>assessed(b).score-assessed(a).score).slice(0,5); return <><Intro kicker="RISK INTELLIGENCE / 16 AUGUST 2026" title="Organizational risk profile" copy="A decision-focused view of exposure, control response, and accountability across the enterprise." action={<Button onClick={()=>go('Risk register')}><Plus size={16}/> Record a risk</Button>}/><div className="metrics"><Metric icon={ShieldCheck} label="Active risks" value={metrics.total} note="Across the enterprise"/><Metric icon={AlertTriangle} label="Outside appetite" value={metrics.appetite} note="Residual score 12+" danger/><Metric icon={ClipboardCheck} label="Treatment coverage" value={`${metrics.coverage}%`} note={`${metrics.actions} open actions`}/><Metric icon={ArrowDownRight} label="Exposure reduction" value={`${metrics.reduction}%`} note="Inherent to residual" positive/></div><div className="overview-grid"><section className="surface"><SectionHead title="Priority risk register" copy="Highest residual exposure requiring attention" action={<button className="text" onClick={()=>go('Risk register')}>View register <ArrowRight size={14}/></button>}/><RiskRows risks={priorities} open={open}/></section><section className="surface map-card"><SectionHead title="Risk landscape" copy="Current assessment distribution"/><Mode value={mode} set={setMode}/><HeatMap risks={risks} mode={mode} compact open={open}/></section></div><div className="lower-grid"><section className="surface"><SectionHead title="Treatment momentum" copy="Progress across open response actions"/><Actions risks={risks} open={open} limit={4}/></section><section className="surface"><SectionHead title="Exposure by category" copy="Residual score contribution"/><CategoryBars risks={risks}/></section></div></> }
function Metric({icon:Icon,label,value,note,danger,positive}) { return <article className={`metric ${danger?'danger':''} ${positive?'positive':''}`}><i><Icon size={17}/></i><div><small>{label}</small><b>{value}</b><span>{note}</span></div></article> }
function RiskRows({risks,open}) { return <div className="risk-rows">{risks.map(r=><button key={r.id} onClick={()=>open(r)}><i className={`level ${assessed(r).level.toLowerCase()}`}/><span><small>{r.reference} / {r.category}</small><b>{r.title}</b></span><span className="owner"><Avatar name={r.owner}/>{r.owner}</span><Score item={assessed(r)}/><ArrowRight size={15}/></button>)}</div> }

function Register({risks,query,setQuery,level,setLevel,open,create}) { return <><Intro kicker="RISK MANAGEMENT" title="Risk register" copy="Create, assess, assign, and monitor every material uncertainty in one accountable record." action={<Button onClick={create}><Plus size={16}/> New risk</Button>}/><section className="surface register"><div className="tools"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reference, risk, owner or category"/></label><label><SlidersHorizontal size={15}/><select value={level} onChange={e=>setLevel(e.target.value)}><option>All levels</option><option>Critical</option><option>High</option><option>Moderate</option><option>Low</option></select></label><span>{risks.length} risks</span></div><div className="table"><table><thead><tr><th>Risk</th><th>Owner / function</th><th>Inherent</th><th>Residual</th><th>Treatment</th><th>Next review</th><th/></tr></thead><tbody>{risks.map(r=><tr key={r.id} onClick={()=>open(r)}><td><small>{r.reference}</small><b>{r.title}</b><span>{r.category}</span></td><td><div className="person"><Avatar name={r.owner}/><span><b>{r.owner}</b><small>{r.business_unit}</small></span></div></td><td><Score item={r.inherent}/></td><td>{r.residual?<Score item={r.residual}/>:<em>Not assessed</em>}</td><td><b>{r.treatment_strategy}</b><small>{r.status}</small></td><td>{new Date(r.review_date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</td><td><ArrowRight size={15}/></td></tr>)}</tbody></table>{!risks.length&&<div className="empty"><Search/><b>No risks found</b><span>Adjust the search or level filter.</span></div>}</div></section></> }

function Mode({value,set}) { return <div className="mode"><button className={value==='inherent'?'active':''} onClick={()=>set('inherent')}>Inherent</button><button className={value==='residual'?'active':''} onClick={()=>set('residual')}>Residual</button></div> }
function HeatMap({risks,mode,compact,open}) { const cell=(l,i)=>risks.filter(r=>r[mode]?.likelihood===l&&r[mode]?.impact===i); return <div className={`heat-wrap ${compact?'compact':''}`}><b className="axis-y">LIKELIHOOD</b><div className="y-labels">{['Almost certain','Likely','Possible','Unlikely','Rare'].map(x=><span key={x}>{compact?x[0]:x}</span>)}</div><div className="heat-grid">{[5,4,3,2,1].flatMap(l=>[1,2,3,4,5].map(i=>{const rs=cell(l,i);return <button key={`${l}-${i}`} className={levelFor(l*i).toLowerCase()} onClick={()=>rs.length===1&&open(rs[0])} aria-label={`${rs.length} risks at likelihood ${l}, impact ${i}`}><b>{rs.length||''}</b>{!compact&&<small>{l*i}</small>}</button>}))}</div><div className="x-labels">{['Insignificant','Minor','Moderate','Major','Severe'].map(x=><span key={x}>{compact?x[0]:x}</span>)}</div><b className="axis-x">IMPACT</b></div> }
function HeatPage({risks,mode,setMode,open}) { return <><Intro kicker="RISK INTELLIGENCE" title="Risk heat map" copy="Compare inherent exposure with the residual position after controls and treatment." action={<Mode value={mode} set={setMode}/>}/><section className="surface heat-page"><div className="heat-head"><SectionHead title={`${mode==='inherent'?'Inherent':'Residual'} exposure matrix`} copy="Select a populated cell to inspect its risks"/><div className="legend">{['low','moderate','high','critical'].map(x=><span key={x}><i className={x}/>{x}</span>)}</div></div><HeatMap risks={risks} mode={mode} open={open}/><p className="map-note"><ShieldCheck size={15}/> Scores use likelihood x impact on a 5 x 5 matrix. Residual assessments remain separate records.</p></section></> }

function Treatments({risks,open}) { const actions=risks.flatMap(r=>r.actions||[]); return <><Intro kicker="RISK RESPONSE" title="Treatment & controls" copy="Track accountable action and verify that controls are changing exposure as intended."/><div className="treatment-metrics"><Metric icon={ClipboardCheck} label="Open actions" value={actions.filter(a=>a.status!=='Complete').length} note="Across active plans"/><Metric icon={AlertTriangle} label="Blocked" value={actions.filter(a=>a.status==='Blocked').length} note="Require support" danger/><Metric icon={ShieldCheck} label="Controls linked" value={risks.reduce((n,r)=>n+(r.controls?.length||0),0)} note="Effectiveness rated"/></div><section className="surface"><SectionHead title="Action portfolio" copy="Delivery progress and ownership"/><Actions risks={risks} open={open}/></section></> }
function Actions({risks,open,limit}) { const actions=risks.flatMap(r=>(r.actions||[]).map(a=>({...a,risk:r}))).slice(0,limit); return <div className="actions">{actions.map(a=><button key={a.id} onClick={()=>open(a.risk)}><i className={a.status==='Blocked'?'blocked':''}><CheckCircle2 size={16}/></i><span><small>{a.risk.reference} / {a.risk.category}</small><b>{a.title}</b><em>{a.owner} / Due {new Date(a.due_date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</em></span><span className="progress"><i><b style={{width:`${a.progress}%`}}/></i><b>{a.progress}%</b></span><strong className={a.status==='Blocked'?'blocked':''}>{a.status}</strong></button>)}</div> }
function CategoryBars({risks}) { const items=Object.entries(risks.reduce((a,r)=>({...a,[r.category]:(a[r.category]||0)+assessed(r).score}),{})).sort((a,b)=>b[1]-a[1]), max=Math.max(...items.map(x=>x[1])); return <div className="bars">{items.map(([name,value])=><div key={name}><span>{name}<b>{value}</b></span><i><b style={{width:`${value/max*100}%`}}/></i></div>)}</div> }

function Reports({risks,metrics}) { const download=()=>window.location.href=`${API}/reports/risk-register.csv`; return <><Intro kicker="MANAGEMENT ASSURANCE" title="Reports" copy="Generate decision-ready views that reconcile directly to the current risk register."/><div className="report-grid"><Report icon={FileBarChart} title="Executive risk summary" copy="Board-level profile, appetite breaches, movement, and treatment priorities." meta="PDF / Management"/><Report icon={FileText} title="Complete risk register" copy="Detailed risk, assessment, ownership, control, and review data." meta="CSV / Operational" action={download}/><Report icon={ClipboardCheck} title="Treatment status" copy="Open, overdue, blocked, and completed actions by owner." meta="PDF / Management"/><Report icon={ShieldCheck} title="Control effectiveness" copy="Design and operating effectiveness across linked risks." meta="CSV / Assurance"/></div><section className="surface preview"><SectionHead title="Executive summary preview" copy="Current organizational position" action={<Button secondary onClick={download}><Download size={15}/> Export register</Button>}/><div className="headlines"><Headline label="RESIDUAL EXPOSURE" value={metrics.appetite} note="risks outside appetite"/><Headline label="EXPOSURE REDUCTION" value={`${metrics.reduction}%`} note="from inherent baseline"/><Headline label="TREATMENT COVERAGE" value={`${metrics.coverage}%`} note="risks with response activity"/></div><div className="priorities"><h3>Management priorities</h3>{[...risks].sort((a,b)=>assessed(b).score-assessed(a).score).slice(0,3).map((r,i)=><div key={r.id}><i>{i+1}</i><span><b>{r.title}</b><small>{r.owner} / {r.business_unit}</small></span><Score item={assessed(r)}/></div>)}</div></section></> }
function Report({icon:Icon,title,copy,meta,action}) { return <article className="report"><i><Icon size={19}/></i><h2>{title}</h2><p>{copy}</p><div><small>{meta}</small><button onClick={action}><Download size={15}/></button></div></article> }
function Headline({label,value,note}) { return <div><small>{label}</small><b>{value}</b><span>{note}</span></div> }

function Drawer({risk,close}) { const reduction=Math.round((risk.inherent.score-assessed(risk).score)/risk.inherent.score*100); return <div className="layer"><div className="layer-scrim" onClick={close}/><aside className="drawer"><header><div><small>{risk.reference} / {risk.category}</small><h2>{risk.title}</h2></div><button onClick={close}><X size={18}/></button></header><div className="drawer-body"><p>{risk.description}</p><div className="owner-card"><Avatar name={risk.owner}/><span><small>RISK OWNER</small><b>{risk.owner}</b><em>{risk.business_unit}</em></span><strong>{risk.status}</strong></div><section><h3>Assessment profile</h3><div className="comparison"><AssessmentCard title="Inherent risk" item={risk.inherent}/><span><ArrowRight/><b>{reduction}%</b><small>reduction</small></span><AssessmentCard title="Residual risk" item={risk.residual}/></div></section><section><h3>Response strategy</h3><div className="details"><Info label="Treatment" value={risk.treatment_strategy}/><Info label="Next review" value={new Date(risk.review_date).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}/><Info label="Controls" value={`${risk.controls?.length||0} linked`}/><Info label="Actions" value={`${risk.actions?.length||0} open`}/></div></section><section><h3>Controls</h3>{risk.controls?.map(c=><div className="control" key={c.id}><i><ShieldCheck size={16}/></i><span><b>{c.title}</b><small>{c.type} / {c.owner}</small></span><strong>{c.effectiveness}</strong></div>)}</section><section><h3>Treatment actions</h3><Actions risks={[risk]} open={()=>{}}/></section></div></aside></div> }
function AssessmentCard({title,item}) { return item?<div className={`assessment ${item.level.toLowerCase()}`}><small>{title}</small><p><b>{item.score}</b><strong>{item.level}</strong></p><span>L{item.likelihood} x I{item.impact}</span></div>:<div className="assessment"><small>{title}</small><b>Not assessed</b></div> }
function Info({label,value}) { return <div><small>{label}</small><b>{value}</b></div> }

function RiskModal({close,submit}) { return <div className="layer modal-layer"><div className="layer-scrim" onClick={close}/><div className="modal"><header><div><small>NEW RISK RECORD</small><h2>Capture and assess exposure</h2></div><button onClick={close}><X size={18}/></button></header><form onSubmit={submit}><section><h3>Risk context</h3><Field name="title" label="Risk title" placeholder="Concise description of the uncertainty" required/><Field name="description" label="Risk statement" placeholder="Describe the cause, uncertain event, and potential impact" textarea required/><div className="form-grid"><Field name="category" label="Category" required/><Field name="unit" label="Business unit" required/><Field name="owner" label="Risk owner" required/><Select name="strategy" label="Treatment" values={['Reduce','Avoid','Transfer','Accept']}/></div><Field name="date" label="Next review date" type="date" required/></section><section><h3>Assess exposure</h3><div className="assessment-form"><div><h4>Inherent risk <small>Before controls</small></h4><div className="form-grid two"><Select name="il" label="Likelihood" values={[1,2,3,4,5]}/><Select name="ii" label="Impact" values={[1,2,3,4,5]}/></div><Field name="inherentRationale" label="Rationale" placeholder="Explain the credible rating scenario" required/></div><div><h4>Residual risk <small>After controls</small></h4><div className="form-grid two"><Select name="rl" label="Likelihood" values={[1,2,3,4,5]}/><Select name="ri" label="Impact" values={[1,2,3,4,5]}/></div><Field name="residualRationale" label="Rationale" placeholder="Explain how controls change exposure" required/></div></div></section><footer><Button secondary onClick={close}>Cancel</Button><Button><ShieldCheck size={16}/> Create risk</Button></footer></form></div></div> }
function Field({label,textarea,...props}) { const Tag=textarea?'textarea':'input'; return <label className="field"><span>{label}</span><Tag {...props}/></label> }
function Select({label,values,...props}) { return <label className="field"><span>{label}</span><select {...props}>{values.map(v=><option key={v}>{v}</option>)}</select></label> }